-- MS SQL DDL ported from MySQL version at C:\workspaces\eclipse-luna-4.4.1\jhu-git\MySQLTranslator\cgds.sql

IF OBJECT_ID('dbo.info', 'U') IS NOT NULL
 DROP TABLE dbo.info

IF OBJECT_ID('dbo.clinical_event_data', 'U') IS NOT NULL
 DROP TABLE dbo.clinical_event_data

IF OBJECT_ID('dbo.clinical_event', 'U') IS NOT NULL
 DROP TABLE dbo.clinical_event

IF OBJECT_ID('dbo.pdb_uniprot_residue_mapping', 'U') IS NOT NULL
 DROP TABLE dbo.pdb_uniprot_residue_mapping

IF OBJECT_ID('dbo.pdb_uniprot_alignment', 'U') IS NOT NULL
 DROP TABLE dbo.pdb_uniprot_alignment

IF OBJECT_ID('dbo.cosmic_mutation', 'U') IS NOT NULL
 DROP TABLE dbo.cosmic_mutation

IF OBJECT_ID('dbo.copy_number_seg_file', 'U') IS NOT NULL
 DROP TABLE dbo.copy_number_seg_file

IF OBJECT_ID('dbo.copy_number_seg', 'U') IS NOT NULL
 DROP TABLE dbo.copy_number_seg

IF OBJECT_ID('dbo.sample_cna_event', 'U') IS NOT NULL
 DROP TABLE dbo.sample_cna_event

IF OBJECT_ID('dbo.cna_event', 'U') IS NOT NULL
 DROP TABLE dbo.cna_event

IF OBJECT_ID('dbo.drug_interaction', 'U') IS NOT NULL
 DROP TABLE dbo.drug_interaction

IF OBJECT_ID('dbo.drug', 'U') IS NOT NULL
 DROP TABLE dbo.drug

IF OBJECT_ID('dbo.pfam_graphics', 'U') IS NOT NULL
 DROP TABLE dbo.pfam_graphics

IF OBJECT_ID('dbo.text_cache', 'U') IS NOT NULL
 DROP TABLE dbo.text_cache

IF OBJECT_ID('dbo.gistic_to_gene', 'U') IS NOT NULL
 DROP TABLE dbo.gistic_to_gene

IF OBJECT_ID('dbo.gistic', 'U') IS NOT NULL
 DROP TABLE dbo.gistic

IF OBJECT_ID('dbo.sanger_cancer_census', 'U') IS NOT NULL
 DROP TABLE dbo.sanger_cancer_census

IF OBJECT_ID('dbo.protein_array_cancer_study', 'U') IS NOT NULL
 DROP TABLE dbo.protein_array_cancer_study

IF OBJECT_ID('dbo.protein_array_data', 'U') IS NOT NULL
 DROP TABLE dbo.protein_array_data

IF OBJECT_ID('dbo.protein_array_target', 'U') IS NOT NULL
 DROP TABLE dbo.protein_array_target

IF OBJECT_ID('dbo.protein_array_info', 'U') IS NOT NULL
 DROP TABLE dbo.protein_array_info

IF OBJECT_ID('dbo.mut_sig', 'U') IS NOT NULL
 DROP TABLE dbo.mut_sig

IF OBJECT_ID('dbo.interaction', 'U') IS NOT NULL
 DROP TABLE dbo.interaction

IF OBJECT_ID('dbo.clinical_attribute_meta', 'U') IS NOT NULL
 DROP TABLE dbo.clinical_attribute_meta

IF OBJECT_ID('dbo.clinical_sample', 'U') IS NOT NULL
 DROP TABLE dbo.clinical_sample

IF OBJECT_ID('dbo.clinical_patient', 'U') IS NOT NULL
 DROP TABLE dbo.clinical_patient

IF OBJECT_ID('dbo.mutation_count', 'U') IS NOT NULL
 DROP TABLE dbo.mutation_count

IF OBJECT_ID('dbo.mutation', 'U') IS NOT NULL
 DROP TABLE dbo.mutation

IF OBJECT_ID('dbo.mutation_event', 'U') IS NOT NULL
 DROP TABLE dbo.mutation_event

IF OBJECT_ID('dbo.structural_variant', 'U') IS NOT NULL
 DROP TABLE dbo.structural_variant

IF OBJECT_ID('dbo.sample_profile', 'U') IS NOT NULL
 DROP TABLE dbo.sample_profile

IF OBJECT_ID('dbo.gene_panel_list', 'U') IS NOT NULL
 DROP TABLE dbo.gene_panel_list

IF OBJECT_ID('dbo.gene_panel', 'U') IS NOT NULL
 DROP TABLE dbo.gene_panel

IF OBJECT_ID('dbo.genetic_profile_samples', 'U') IS NOT NULL
 DROP TABLE dbo.genetic_profile_samples

IF OBJECT_ID('dbo.genetic_alteration', 'U') IS NOT NULL
 DROP TABLE dbo.genetic_alteration

IF OBJECT_ID('dbo.genetic_profile', 'U') IS NOT NULL
 DROP TABLE dbo.genetic_profile

IF OBJECT_ID('dbo.uniprot_id_mapping', 'U') IS NOT NULL
 DROP TABLE dbo.uniprot_id_mapping

IF OBJECT_ID('dbo.gene_alias', 'U') IS NOT NULL
 DROP TABLE dbo.gene_alias

IF OBJECT_ID('dbo.gene', 'U') IS NOT NULL
 DROP TABLE dbo.gene

IF OBJECT_ID('dbo.sample_list_list', 'U') IS NOT NULL
 DROP TABLE dbo.sample_list_list

IF OBJECT_ID('dbo.sample_list', 'U') IS NOT NULL
 DROP TABLE dbo.sample_list

IF OBJECT_ID('dbo.sample', 'U') IS NOT NULL
 DROP TABLE dbo.sample

IF OBJECT_ID('dbo.patient', 'U') IS NOT NULL
 DROP TABLE dbo.patient

IF OBJECT_ID('dbo.authorities', 'U') IS NOT NULL
 DROP TABLE dbo.authorities

IF OBJECT_ID('dbo.users', 'U') IS NOT NULL
 DROP TABLE dbo.users

IF OBJECT_ID('dbo.cancer_study', 'U') IS NOT NULL
 DROP TABLE dbo.cancer_study

IF OBJECT_ID('dbo.type_of_cancer', 'U') IS NOT NULL
 DROP TABLE dbo.type_of_cancer



GO

CREATE TABLE [statements so that refererenced
-- tables are created before referring tables.
-- DROP TABLE statements are here in the reverse order.
-- --------------------------------------------------------

DROP TABLE IF EXISTS info;
DROP TABLE IF EXISTS clinical_event_data;
DROP TABLE IF EXISTS clinical_event;
DROP TABLE IF EXISTS pdb_uniprot_residue_mapping;
DROP TABLE IF EXISTS pdb_uniprot_alignment;
DROP TABLE IF EXISTS cosmic_mutation;
DROP TABLE IF EXISTS copy_number_seg_file;
DROP TABLE IF EXISTS copy_number_seg;
DROP TABLE IF EXISTS sample_cna_event;
DROP TABLE IF EXISTS cna_event;
DROP TABLE IF EXISTS drug_interaction;
DROP TABLE IF EXISTS drug;
DROP TABLE IF EXISTS pfam_graphics;
DROP TABLE IF EXISTS text_cache;
DROP TABLE IF EXISTS gistic_to_gene;
DROP TABLE IF EXISTS gistic;
DROP TABLE IF EXISTS sanger_cancer_census;
DROP TABLE IF EXISTS protein_array_cancer_study;
DROP TABLE IF EXISTS protein_array_data;
DROP TABLE IF EXISTS protein_array_target;
DROP TABLE IF EXISTS protein_array_info;
DROP TABLE IF EXISTS mut_sig;
DROP TABLE IF EXISTS interaction;
DROP TABLE IF EXISTS clinical_attribute_meta;
DROP TABLE IF EXISTS clinical_sample;
DROP TABLE IF EXISTS clinical_patient;
DROP TABLE IF EXISTS mutation_count;
DROP TABLE IF EXISTS mutation;
DROP TABLE IF EXISTS mutation_event;
DROP TABLE IF EXISTS structural_variant;
DROP TABLE IF EXISTS sample_profile;
DROP TABLE IF EXISTS gene_panel_list;
DROP TABLE IF EXISTS gene_panel;
DROP TABLE IF EXISTS genetic_profile_samples;
DROP TABLE IF EXISTS genetic_alteration;
DROP TABLE IF EXISTS genetic_profile;
DROP TABLE IF EXISTS uniprot_id_mapping;
DROP TABLE IF EXISTS gene_alias;
DROP TABLE IF EXISTS gene;
DROP TABLE IF EXISTS sample_list_list;
DROP TABLE IF EXISTS sample_list;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS cancer_study;
DROP TABLE IF EXISTS type_of_cancer;

-- --------------------------------------------------------
CREATE TABLE type_of_cancer] (
   [TYPE_OF_CANCER_ID] VARCHAR(63) NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [CLINICAL_TRIAL_KEYWORDS] VARCHAR(1024) NOT NULL
,  [DEDICATED_COLOR] CHAR(31) NOT NULL
,  [SHORT_NAME] VARCHAR(127)
,  [PARENT] VARCHAR(63)
)

CREATE TABLE [type_of_cancer] (
   [TYPE_OF_CANCER_ID] VARCHAR(63) NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [CLINICAL_TRIAL_KEYWORDS] VARCHAR(1024) NOT NULL
,  [DEDICATED_COLOR] CHAR(31) NOT NULL
,  [SHORT_NAME] VARCHAR(127)
,  [PARENT] VARCHAR(63)
)

CREATE TABLE [cancer_study] (
   [CANCER_STUDY_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [CANCER_STUDY_IDENTIFIER] VARCHAR(255)
,  [TYPE_OF_CANCER_ID] VARCHAR(25) NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [SHORT_NAME] VARCHAR(64) NOT NULL
,  [DESCRIPTION] VARCHAR(1024) NOT NULL
,  [PUBLIC] BIT NOT NULL
,  [PMID] VARCHAR(20) DEFAULT NULL
,  [CITATION] VARCHAR(200) DEFAULT NULL
,  [GROUPS] VARCHAR(200) DEFAULT NULL
,  [STATUS] INTEGER DEFAULT NULL
,  [IMPORT_DATE] DATETIME DEFAULT NULL
)

CREATE TABLE [users] (
   [EMAIL] VARCHAR(128) NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [ENABLED] BIT NOT NULL
)

CREATE TABLE [authorities] (
   [EMAIL] VARCHAR(128) NOT NULL
,  [AUTHORITY] VARCHAR(255) NOT NULL
)

CREATE TABLE [patient] (
   [INTERNAL_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [STABLE_ID] VARCHAR(50) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
)

CREATE TABLE [sample] (
   [INTERNAL_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [STABLE_ID] VARCHAR(50) NOT NULL
,  [SAMPLE_TYPE] VARCHAR(255) NOT NULL
,  [PATIENT_ID] INTEGER NOT NULL
,  [TYPE_OF_CANCER_ID] VARCHAR(25) NOT NULL
)

CREATE TABLE [sample_list] (
   [LIST_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [STABLE_ID] VARCHAR(255) NOT NULL
,  [CATEGORY] VARCHAR(255) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [DESCRIPTION] TEXT
)

CREATE TABLE [sample_list_list] (
   [LIST_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
)

CREATE TABLE [gene] (
   [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [HUGO_GENE_SYMBOL] VARCHAR(255) NOT NULL
,  [TYPE] VARCHAR(50)
,  [CYTOBAND] VARCHAR(50)
,  [LENGTH] INTEGER
)

CREATE TABLE [gene_alias] (
   [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [GENE_ALIAS] VARCHAR(255) NOT NULL
)

CREATE TABLE [uniprot_id_mapping] (
   [UNIPROT_ACC] VARCHAR(255) NOT NULL
,  [UNIPROT_ID] VARCHAR(255) NOT NULL
,  [ENTREZ_GENE_ID] INTEGER
)

CREATE TABLE [genetic_profile] (
   [GENETIC_PROFILE_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [STABLE_ID] VARCHAR(255) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [GENETIC_ALTERATION_TYPE] VARCHAR(255) NOT NULL
,  [DATATYPE] VARCHAR(255) NOT NULL
,  [NAME] VARCHAR(255) NOT NULL
,  [DESCRIPTION] TEXT
,  [SHOW_PROFILE_IN_ANALYSIS_TAB] BINARY(1) NOT NULL
)

CREATE TABLE [genetic_alteration] (
   [GENETIC_PROFILE_ID] INTEGER NOT NULL
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [VALUES] TEXT NOT NULL
)

CREATE TABLE [genetic_profile_samples] (
   [GENETIC_PROFILE_ID] INTEGER NOT NULL
,  [ORDERED_SAMPLE_LIST] TEXT NOT NULL
)

CREATE TABLE [gene_panel] (
   [INTERNAL_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [STABLE_ID] VARCHAR(255) NOT NULL
,  [DESCRIPTION] TEXT
)

CREATE TABLE [gene_panel_list] (
   [INTERNAL_ID] INTEGER NOT NULL
,  [GENE_ID] INTEGER NOT NULL
)

CREATE TABLE [sample_profile] (
   [SAMPLE_ID] INTEGER NOT NULL
,  [GENETIC_PROFILE_ID] INTEGER NOT NULL
,  [PANEL_ID] INTEGER DEFAULT NULL
)

CREATE TABLE [structural_variant] (
   [SAMPLE_ID] INTEGER NOT NULL
,  [INTERNAL_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [BREAKPOINT_TYPE] VARCHAR(25)
,  [ANNOTATION] VARCHAR(255)
,  [COMMENTS] VARCHAR(2048)
,  [CONFIDENCE_CLASS] VARCHAR(25)
,  [CONNECTION_TYPE] VARCHAR(25)
,  [EVENT_INFO] VARCHAR(255)
,  [MAPQ] INTEGER
,  [NORMAL_READ_COUNT] INTEGER
,  [NORMAL_VARIANT_COUNT] INTEGER
,  [PAIRED_END_READ_SUPPORT] VARCHAR(255)
,  [SITE1_CHROM] VARCHAR(25)
,  [SITE1_DESC] VARCHAR(255)
,  [SITE1_ENTREZ_GENE_ID] INTEGER
,  [SITE1_POS] INTEGER
,  [SITE2_CHROM] VARCHAR(25)
,  [SITE2_DESC] VARCHAR(255)
,  [SITE2_ENTREZ_GENE_ID] INTEGER
,  [SITE2_POS] INTEGER
,  [SPLIT_READ_SUPPORT] VARCHAR(255)
,  [SV_CLASS_NAME] VARCHAR(25)
,  [SV_DESC] VARCHAR(255)
,  [SV_LENGTH] INTEGER
,  [TUMOR_READ_COUNT] INTEGER
,  [TUMOR_VARIANT_COUNT] INTEGER
,  [VARIANT_STATUS_NAME] VARCHAR(255)
,  [GENETIC_PROFILE_ID] INTEGER NOT NULL
)

CREATE TABLE [mutation_event] (
   [MUTATION_EVENT_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [CHR] VARCHAR(5)
,  [START_POSITION] BIGINT
,  [END_POSITION] BIGINT
,  [REFERENCE_ALLELE] VARCHAR(400)
,  [TUMOR_SEQ_ALLELE] VARCHAR(400)
,  [PROTEIN_CHANGE] VARCHAR(255)
,  [MUTATION_TYPE] VARCHAR(255) COMMENT 'e.g. Missense, Nonsence, etc.'
,  [FUNCTIONAL_IMPACT_SCORE] VARCHAR(50) COMMENT 'Result from OMA/XVAR.'
,  [FIS_VALUE] REAL
,  [LINK_XVAR] VARCHAR(500) COMMENT 'Link to OMA/XVAR Landing Page for the specific mutation.'
,  [LINK_PDB] VARCHAR(500)
,  [LINK_MSA] VARCHAR(500)
,  [NCBI_BUILD] VARCHAR(10)
,  [STRAND] VARCHAR(2)
,  [VARIANT_TYPE] VARCHAR(15)
,  [DB_SNP_RS] VARCHAR(25)
,  [DB_SNP_VAL_STATUS] VARCHAR(255)
,  [ONCOTATOR_DBSNP_RS] VARCHAR(255)
,  [ONCOTATOR_REFSEQ_MRNA_ID] VARCHAR(64)
,  [ONCOTATOR_CODON_CHANGE] VARCHAR(255)
,  [ONCOTATOR_UNIPROT_ENTRY_NAME] VARCHAR(64)
,  [ONCOTATOR_UNIPROT_ACCESSION] VARCHAR(64)
,  [ONCOTATOR_PROTEIN_POS_START] INTEGER
,  [ONCOTATOR_PROTEIN_POS_END] INTEGER
,  [CANONICAL_TRANSCRIPT] BIT
,  [KEYWORD] VARCHAR(50) DEFAULT NULL COMMENT 'e.g. truncating, V200 Missense, E338del, '
)

CREATE TABLE [mutation] (
   [MUTATION_EVENT_ID] INTEGER NOT NULL
,  [GENETIC_PROFILE_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
,  [ENTREZ_GENE_ID] INTEGER NOT NULL, # this is included here for performance
,  [CENTER] VARCHAR(100)
,  [SEQUENCER] VARCHAR(255)
,  [MUTATION_STATUS] VARCHAR(25) COMMENT 'Germline, Somatic or LOH.'
,  [VALIDATION_STATUS] VARCHAR(25)
,  [TUMOR_SEQ_ALLELE1] VARCHAR(255)
,  [TUMOR_SEQ_ALLELE2] VARCHAR(255)
,  [MATCHED_NORM_SAMPLE_BARCODE] VARCHAR(255)
,  [MATCH_NORM_SEQ_ALLELE1] VARCHAR(255)
,  [MATCH_NORM_SEQ_ALLELE2] VARCHAR(255)
,  [TUMOR_VALIDATION_ALLELE1] VARCHAR(255)
,  [TUMOR_VALIDATION_ALLELE2] VARCHAR(255)
,  [MATCH_NORM_VALIDATION_ALLELE1] VARCHAR(255)
,  [MATCH_NORM_VALIDATION_ALLELE2] VARCHAR(255)
,  [VERIFICATION_STATUS] VARCHAR(10)
,  [SEQUENCING_PHASE] VARCHAR(100)
,  [SEQUENCE_SOURCE] VARCHAR(255) NOT NULL
,  [VALIDATION_METHOD] VARCHAR(255)
,  [SCORE] VARCHAR(100)
,  [BAM_FILE] VARCHAR(255)
,  [TUMOR_ALT_COUNT] INTEGER
,  [TUMOR_REF_COUNT] INTEGER
,  [NORMAL_ALT_COUNT] INTEGER
,  [NORMAL_REF_COUNT] INTEGER
,  [AMINO_ACID_CHANGE] VARCHAR(255)
)

CREATE TABLE [mutation_count] (
   [GENETIC_PROFILE_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
,  [MUTATION_COUNT] INTEGER NOT NULL
)

CREATE TABLE [clinical_patient] (
   [INTERNAL_ID] INTEGER NOT NULL
,  [ATTR_ID] VARCHAR(255) NOT NULL
,  [ATTR_VALUE] VARCHAR(255) NOT NULL
)

CREATE TABLE [clinical_sample] (
   [INTERNAL_ID] INTEGER NOT NULL
,  [ATTR_ID] VARCHAR(255) NOT NULL
,  [ATTR_VALUE] VARCHAR(255) NOT NULL
)

CREATE TABLE [clinical_attribute_meta] (
   [ATTR_ID] VARCHAR(255) NOT NULL
,  [DISPLAY_NAME] VARCHAR(255) NOT NULL
,  [DESCRIPTION] VARCHAR(2048) NOT NULL
,  [DATATYPE] VARCHAR(255) NOT NULL COMMENT 'NUMBER, BOOLEAN, or STRING'
,  [PATIENT_ATTRIBUTE] BIT NOT NULL
,  [PRIORITY] VARCHAR(255) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
)

CREATE TABLE [interaction] (
   [GENE_A] BIGINT NOT NULL
,  [GENE_B] BIGINT NOT NULL
,  [INTERACTION_TYPE] VARCHAR(256) NOT NULL
,  [DATA_SOURCE] VARCHAR(256) NOT NULL
,  [EXPERIMENT_TYPES] VARCHAR(1024) NOT NULL
,  [PMIDS] VARCHAR(1024) NOT NULL
)

CREATE TABLE [mut_sig] (
   [CANCER_STUDY_ID] INTEGER NOT NULL
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [RANK] INTEGER NOT NULL
,  [NumBasesCovered] INTEGER NOT NULL
,  [NumMutations] INTEGER NOT NULL
,  [P_VALUE] REAL NOT NULL
,  [Q_VALUE] REAL NOT NULL
)

CREATE TABLE [protein_array_info] (
   [PROTEIN_ARRAY_ID] VARCHAR(50) NOT NULL
,  [TYPE] VARCHAR(50) NOT NULL
,  [GENE_SYMBOL] VARCHAR(50) NOT NULL
,  [TARGET_RESIDUE] VARCHAR(20) default NULL
)

CREATE TABLE [protein_array_target] (
   [PROTEIN_ARRAY_ID] VARCHAR(50) NOT NULL
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
)

CREATE TABLE [protein_array_data] (
   [PROTEIN_ARRAY_ID] VARCHAR(50) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
,  [ABUNDANCE] FLOAT NOT NULL
)

CREATE TABLE [protein_array_cancer_study] (
   [PROTEIN_ARRAY_ID] VARCHAR(50) NOT NULL
,  [CANCER_STUDY_ID] INTEGER NOT NULL
)

CREATE TABLE [sanger_cancer_census] (
   [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [CANCER_SOMATIC_MUT] TINYINT NOT NULL
,  [CANCER_GERMLINE_MUT] TINYINT NOT NULL
,  [TUMOR_TYPES_SOMATIC_MUT] TEXT NOT NULL
,  [TUMOR_TYPES_GERMLINE_MUT] TEXT NOT NULL
,  [CANCER_SYNDROME] TEXT NOT NULL
,  [TISSUE_TYPE] TEXT NOT NULL
,  [MUTATION_TYPE] TEXT NOT NULL
,  [TRANSLOCATION_PARTNER] TEXT NOT NULL
,  [OTHER_GERMLINE_MUT] TINYINT NOT NULL
,  [OTHER_DISEASE] TEXT NOT NULL
)

CREATE TABLE [gistic] (
   [GISTIC_ROI_ID] BIGINT NOT NULL IDENTITY(1,1)
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [CHROMOSOME] INTEGER NOT NULL
,  [CYTOBAND] VARCHAR(255) NOT NULL
,  [WIDE_PEAK_START] INTEGER NOT NULL
,  [WIDE_PEAK_END] INTEGER NOT NULL
,  [Q_VALUE] FLOAT NOT NULL
,  [AMP] TINYINT NOT NULL
)

CREATE TABLE [gistic_to_gene] (
   [GISTIC_ROI_ID] BIGINT NOT NULL
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
)

CREATE TABLE [text_cache] (
   [HASH_KEY] VARCHAR(32) NOT NULL
,  [TEXT] TEXT NOT NULL
,  [DATE_TIME_STAMP] DATETIME NOT NULL
)

CREATE TABLE [pfam_graphics] (
   [UNIPROT_ACC] VARCHAR(255) NOT NULL
,  [JSON_DATA] TEXT NOT NULL
)

CREATE TABLE [drug] (
   [DRUG_ID] CHAR(30) NOT NULL
,  [DRUG_RESOURCE] VARCHAR(255) NOT NULL
,  [DRUG_NAME] VARCHAR(255) NOT NULL
,  [DRUG_SYNONYMS] VARCHAR(4096) DEFAULT NULL
,  [DRUG_DESCRIPTION] VARCHAR(4096) DEFAULT NULL
,  [DRUG_XREF] VARCHAR(4096) DEFAULT NULL
,  [DRUG_ATC_CODE] VARCHAR(1024) DEFAULT NULL
,  [DRUG_APPROVED] INTEGER DEFAULT 0
,  [DRUG_CANCERDRUG] INTEGER DEFAULT 0
,  [DRUG_NUTRACEUTICAL] INTEGER DEFAULT 0
,  [DRUG_NUMOFTRIALS] INTEGER DEFAULT -1
)

CREATE TABLE [drug_interaction] (
   [DRUG] CHAR(30) NOT NULL
,  [TARGET] BIGINT NOT NULL
,  [INTERACTION_TYPE] CHAR(50) NOT NULL
,  [DATA_SOURCE] VARCHAR(256) NOT NULL
,  [EXPERIMENT_TYPES] VARCHAR(1024) DEFAULT NULL
,  [PMIDS] VARCHAR(1024) DEFAULT NULL
)

CREATE TABLE [cna_event] (
   [CNA_EVENT_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [ALTERATION] TINYINT NOT NULL
)

CREATE TABLE [sample_cna_event] (
   [CNA_EVENT_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
,  [GENETIC_PROFILE_ID] INTEGER NOT NULL
)

CREATE TABLE [copy_number_seg] (
   [SEG_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [SAMPLE_ID] INTEGER NOT NULL
,  [CHR] VARCHAR(5) NOT NULL
,  [START] INTEGER NOT NULL
,  [END] INTEGER NOT NULL
,  [NUM_PROBES] INTEGER NOT NULL
,  [SEGMENT_MEAN] FLOAT NOT NULL
)

CREATE TABLE [copy_number_seg_file] (
   [SEG_FILE_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [CANCER_STUDY_ID] INTEGER NOT NULL
,  [REFERENCE_GENOME_ID] VARCHAR(10) NOT NULL
,  [DESCRIPTION] VARCHAR(255) NOT NULL
,  [FILENAME] VARCHAR(255) NOT NULL
)

CREATE TABLE [cosmic_mutation] (
   [COSMIC_MUTATION_ID] VARCHAR(30) NOT NULL
,  [CHR] VARCHAR(5)
,  [START_POSITION] BIGINT
,  [REFERENCE_ALLELE] VARCHAR(255)
,  [TUMOR_SEQ_ALLELE] VARCHAR(255)
,  [STRAND] VARCHAR(2)
,  [CODON_CHANGE] VARCHAR(255)
,  [ENTREZ_GENE_ID] INTEGER NOT NULL
,  [PROTEIN_CHANGE] VARCHAR(255) NOT NULL
,  [COUNT] INTEGER NOT NULL
,  [KEYWORD] VARCHAR(50) DEFAULT NULL
)

CREATE TABLE [pdb_uniprot_alignment] (
   [ALIGNMENT_ID] INTEGER NOT NULL
,  [PDB_ID] CHAR(4) NOT NULL
,  [CHAIN] CHAR(1) NOT NULL
,  [UNIPROT_ID] VARCHAR(50) NOT NULL
,  [PDB_FROM] VARCHAR(10) NOT NULL
,  [PDB_TO] VARCHAR(10) NOT NULL
,  [UNIPROT_FROM] INTEGER NOT NULL
,  [UNIPROT_TO] INTEGER NOT NULL
,  [EVALUE] REAL
,  [IDENTITY] REAL
,  [IDENTP] REAL
,  [UNIPROT_ALIGN] TEXT
,  [PDB_ALIGN] TEXT
,  [MIDLINE_ALIGN] TEXT
)

CREATE TABLE [pdb_uniprot_residue_mapping] (
   [ALIGNMENT_ID] INTEGER NOT NULL
,  [PDB_POSITION] INTEGER NOT NULL
,  [PDB_INSERTION_CODE] CHAR(1) DEFAULT NULL
,  [UNIPROT_POSITION] INTEGER NOT NULL
,  [MATCH] CHAR(1)
)

CREATE TABLE [clinical_event] (
   [CLINICAL_EVENT_ID] INTEGER NOT NULL IDENTITY(1,1)
,  [PATIENT_ID] INTEGER NOT NULL
,  [START_DATE] INTEGER NOT NULL
,  [STOP_DATE] INTEGER
,  [EVENT_TYPE] VARCHAR(20) NOT NULL
)

CREATE TABLE [clinical_event_data] (
   [CLINICAL_EVENT_ID] INTEGER NOT NULL
,  [KEY] VARCHAR(255) NOT NULL
,  [VALUE] VARCHAR(5000) NOT NULL
)

CREATE TABLE [info] (
   [DB_SCHEMA_VERSION] VARCHAR(24)
)



GO

