USE [master]
GO

/****** Object:  Database [LSST]    Script Date: 11/21/2019 1:14:04 PM ******/
CREATE DATABASE [LSST]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LSST', FILENAME = N'/var/opt/mssql/data/LSST.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [STRIPEFG] 
( NAME = N'stripe01', FILENAME = N'/var/opt/mssql/data/stripe01.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe02', FILENAME = N'/var/opt/mssql/data2/stripe02.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe03', FILENAME = N'/var/opt/mssql/data3/stripe03.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe04', FILENAME = N'/var/opt/mssql/data4/stripe04.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe05', FILENAME = N'/var/opt/mssql/data5/stripe05.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe06', FILENAME = N'/var/opt/mssql/data6/stripe06.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB ),
( NAME = N'stripe07', FILENAME = N'/var/opt/mssql/data7/stripe07.ndf' , SIZE = 5GB , MAXSIZE = UNLIMITED, FILEGROWTH = 500MB )

 LOG ON 
( NAME = N'LSST_log', FILENAME = N'/var/opt/mssql/data/LSST_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LSST].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LSST] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LSST] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LSST] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LSST] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LSST] SET ARITHABORT OFF 
GO

ALTER DATABASE [LSST] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LSST] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LSST] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LSST] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LSST] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LSST] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LSST] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LSST] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LSST] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LSST] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LSST] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LSST] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LSST] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LSST] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LSST] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LSST] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LSST] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LSST] SET RECOVERY FULL 
GO

ALTER DATABASE [LSST] SET  MULTI_USER 
GO

ALTER DATABASE [LSST] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LSST] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LSST] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LSST] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LSST] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LSST] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LSST] SET  READ_WRITE 
GO


