use LSST20
go



GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ForcedSource_1025](
	[deepSourceId] [bigint] NOT NULL,
	[scienceCcdExposureId] [bigint] NOT NULL,
	[psfFlux] [real] NULL,
	[psfFluxSigma] [real] NULL,
	[flagBadMeasCentroid] [bit] NOT NULL,
	[flagPixEdge] [bit] NOT NULL,
	[flagPixInterpAny] [bit] NOT NULL,
	[flagPixInterpCen] [bit] NOT NULL,
	[flagPixSaturAny] [bit] NOT NULL,
	[flagPixSaturCen] [bit] NOT NULL,
	[flagBadPsfFlux] [bit] NOT NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[deepSourceId] ASC,
	[scienceCcdExposureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION=PAGE) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ForcedSourceFullOverlap_1025](
	[deepSourceId] [bigint] NOT NULL,
	[scienceCcdExposureId] [bigint] NOT NULL,
	[psfFlux] [real] NULL,
	[psfFluxSigma] [real] NULL,
	[flagBadMeasCentroid] [bit] NOT NULL,
	[flagPixEdge] [bit] NOT NULL,
	[flagPixInterpAny] [bit] NOT NULL,
	[flagPixInterpCen] [bit] NOT NULL,
	[flagPixSaturAny] [bit] NOT NULL,
	[flagPixSaturCen] [bit] NOT NULL,
	[flagBadPsfFlux] [bit] NOT NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL
) ON [PRIMARY]

GO
CREATE CLUSTERED INDEX [idx_fcdsrcflolap_1025_dscid_scicexpid] ON [dbo].[ForcedSourceFullOverlap_1025]
(
	[deepSourceId] ASC,
	[scienceCcdExposureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION=PAGE) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Object_1025](
	[deepSourceId] [bigint] NOT NULL,
	[ra] [float] NOT NULL,
	[decl] [float] NOT NULL,
	[raVar] [float] NULL,
	[declVar] [float] NULL,
	[radeclCov] [float] NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL,
	[u_psfFlux] [float] NULL,
	[u_psfFluxSigma] [float] NULL,
	[u_apFlux] [float] NULL,
	[u_apFluxSigma] [float] NULL,
	[u_modelFlux] [float] NULL,
	[u_modelFluxSigma] [float] NULL,
	[u_instFlux] [float] NULL,
	[u_instFluxSigma] [float] NULL,
	[u_apCorrection] [float] NULL,
	[u_apCorrectionSigma] [float] NULL,
	[u_shapeIx] [float] NULL,
	[u_shapeIy] [float] NULL,
	[u_shapeIxVar] [float] NULL,
	[u_shapeIyVar] [float] NULL,
	[u_shapeIxIyCov] [float] NULL,
	[u_shapeIxx] [float] NULL,
	[u_shapeIyy] [float] NULL,
	[u_shapeIxy] [float] NULL,
	[u_shapeIxxVar] [float] NULL,
	[u_shapeIyyVar] [float] NULL,
	[u_shapeIxyVar] [float] NULL,
	[u_shapeIxxIyyCov] [float] NULL,
	[u_shapeIxxIxyCov] [float] NULL,
	[u_shapeIyyIxyCov] [float] NULL,
	[u_extendedness] [float] NULL,
	[u_flagNegative] [bit] NULL,
	[u_flagBadMeasCentroid] [bit] NULL,
	[u_flagPixEdge] [bit] NULL,
	[u_flagPixInterpAny] [bit] NULL,
	[u_flagPixInterpCen] [bit] NULL,
	[u_flagPixSaturAny] [bit] NULL,
	[u_flagPixSaturCen] [bit] NULL,
	[u_flagBadPsfFlux] [bit] NULL,
	[u_flagBadApFlux] [bit] NULL,
	[u_flagBadModelFlux] [bit] NULL,
	[u_flagBadInstFlux] [bit] NULL,
	[u_flagBadCentroid] [bit] NULL,
	[u_flagBadShape] [bit] NULL,
	[g_psfFlux] [float] NULL,
	[g_psfFluxSigma] [float] NULL,
	[g_apFlux] [float] NULL,
	[g_apFluxSigma] [float] NULL,
	[g_modelFlux] [float] NULL,
	[g_modelFluxSigma] [float] NULL,
	[g_instFlux] [float] NULL,
	[g_instFluxSigma] [float] NULL,
	[g_apCorrection] [float] NULL,
	[g_apCorrectionSigma] [float] NULL,
	[g_shapeIx] [float] NULL,
	[g_shapeIy] [float] NULL,
	[g_shapeIxVar] [float] NULL,
	[g_shapeIyVar] [float] NULL,
	[g_shapeIxIyCov] [float] NULL,
	[g_shapeIxx] [float] NULL,
	[g_shapeIyy] [float] NULL,
	[g_shapeIxy] [float] NULL,
	[g_shapeIxxVar] [float] NULL,
	[g_shapeIyyVar] [float] NULL,
	[g_shapeIxyVar] [float] NULL,
	[g_shapeIxxIyyCov] [float] NULL,
	[g_shapeIxxIxyCov] [float] NULL,
	[g_shapeIyyIxyCov] [float] NULL,
	[g_extendedness] [float] NULL,
	[g_flagNegative] [bit] NULL,
	[g_flagBadMeasCentroid] [bit] NULL,
	[g_flagPixEdge] [bit] NULL,
	[g_flagPixInterpAny] [bit] NULL,
	[g_flagPixInterpCen] [bit] NULL,
	[g_flagPixSaturAny] [bit] NULL,
	[g_flagPixSaturCen] [bit] NULL,
	[g_flagBadPsfFlux] [bit] NULL,
	[g_flagBadApFlux] [bit] NULL,
	[g_flagBadModelFlux] [bit] NULL,
	[g_flagBadInstFlux] [bit] NULL,
	[g_flagBadCentroid] [bit] NULL,
	[g_flagBadShape] [bit] NULL,
	[r_psfFlux] [float] NULL,
	[r_psfFluxSigma] [float] NULL,
	[r_apFlux] [float] NULL,
	[r_apFluxSigma] [float] NULL,
	[r_modelFlux] [float] NULL,
	[r_modelFluxSigma] [float] NULL,
	[r_instFlux] [float] NULL,
	[r_instFluxSigma] [float] NULL,
	[r_apCorrection] [float] NULL,
	[r_apCorrectionSigma] [float] NULL,
	[r_shapeIx] [float] NULL,
	[r_shapeIy] [float] NULL,
	[r_shapeIxVar] [float] NULL,
	[r_shapeIyVar] [float] NULL,
	[r_shapeIxIyCov] [float] NULL,
	[r_shapeIxx] [float] NULL,
	[r_shapeIyy] [float] NULL,
	[r_shapeIxy] [float] NULL,
	[r_shapeIxxVar] [float] NULL,
	[r_shapeIyyVar] [float] NULL,
	[r_shapeIxyVar] [float] NULL,
	[r_shapeIxxIyyCov] [float] NULL,
	[r_shapeIxxIxyCov] [float] NULL,
	[r_shapeIyyIxyCov] [float] NULL,
	[r_extendedness] [float] NULL,
	[r_flagNegative] [bit] NULL,
	[r_flagBadMeasCentroid] [bit] NULL,
	[r_flagPixEdge] [bit] NULL,
	[r_flagPixInterpAny] [bit] NULL,
	[r_flagPixInterpCen] [bit] NULL,
	[r_flagPixSaturAny] [bit] NULL,
	[r_flagPixSaturCen] [bit] NULL,
	[r_flagBadPsfFlux] [bit] NULL,
	[r_flagBadApFlux] [bit] NULL,
	[r_flagBadModelFlux] [bit] NULL,
	[r_flagBadInstFlux] [bit] NULL,
	[r_flagBadCentroid] [bit] NULL,
	[r_flagBadShape] [bit] NULL,
	[i_psfFlux] [float] NULL,
	[i_psfFluxSigma] [float] NULL,
	[i_apFlux] [float] NULL,
	[i_apFluxSigma] [float] NULL,
	[i_modelFlux] [float] NULL,
	[i_modelFluxSigma] [float] NULL,
	[i_instFlux] [float] NULL,
	[i_instFluxSigma] [float] NULL,
	[i_apCorrection] [float] NULL,
	[i_apCorrectionSigma] [float] NULL,
	[i_shapeIx] [float] NULL,
	[i_shapeIy] [float] NULL,
	[i_shapeIxVar] [float] NULL,
	[i_shapeIyVar] [float] NULL,
	[i_shapeIxIyCov] [float] NULL,
	[i_shapeIxx] [float] NULL,
	[i_shapeIyy] [float] NULL,
	[i_shapeIxy] [float] NULL,
	[i_shapeIxxVar] [float] NULL,
	[i_shapeIyyVar] [float] NULL,
	[i_shapeIxyVar] [float] NULL,
	[i_shapeIxxIyyCov] [float] NULL,
	[i_shapeIxxIxyCov] [float] NULL,
	[i_shapeIyyIxyCov] [float] NULL,
	[i_extendedness] [float] NULL,
	[i_flagNegative] [bit] NULL,
	[i_flagBadMeasCentroid] [bit] NULL,
	[i_flagPixEdge] [bit] NULL,
	[i_flagPixInterpAny] [bit] NULL,
	[i_flagPixInterpCen] [bit] NULL,
	[i_flagPixSaturAny] [bit] NULL,
	[i_flagPixSaturCen] [bit] NULL,
	[i_flagBadPsfFlux] [bit] NULL,
	[i_flagBadApFlux] [bit] NULL,
	[i_flagBadModelFlux] [bit] NULL,
	[i_flagBadInstFlux] [bit] NULL,
	[i_flagBadCentroid] [bit] NULL,
	[i_flagBadShape] [bit] NULL,
	[z_psfFlux] [float] NULL,
	[z_psfFluxSigma] [float] NULL,
	[z_apFlux] [float] NULL,
	[z_apFluxSigma] [float] NULL,
	[z_modelFlux] [float] NULL,
	[z_modelFluxSigma] [float] NULL,
	[z_instFlux] [float] NULL,
	[z_instFluxSigma] [float] NULL,
	[z_apCorrection] [float] NULL,
	[z_apCorrectionSigma] [float] NULL,
	[z_shapeIx] [float] NULL,
	[z_shapeIy] [float] NULL,
	[z_shapeIxVar] [float] NULL,
	[z_shapeIyVar] [float] NULL,
	[z_shapeIxIyCov] [float] NULL,
	[z_shapeIxx] [float] NULL,
	[z_shapeIyy] [float] NULL,
	[z_shapeIxy] [float] NULL,
	[z_shapeIxxVar] [float] NULL,
	[z_shapeIyyVar] [float] NULL,
	[z_shapeIxyVar] [float] NULL,
	[z_shapeIxxIyyCov] [float] NULL,
	[z_shapeIxxIxyCov] [float] NULL,
	[z_shapeIyyIxyCov] [float] NULL,
	[z_extendedness] [float] NULL,
	[z_flagNegative] [bit] NULL,
	[z_flagBadMeasCentroid] [bit] NULL,
	[z_flagPixEdge] [bit] NULL,
	[z_flagPixInterpAny] [bit] NULL,
	[z_flagPixInterpCen] [bit] NULL,
	[z_flagPixSaturAny] [bit] NULL,
	[z_flagPixSaturCen] [bit] NULL,
	[z_flagBadPsfFlux] [bit] NULL,
	[z_flagBadApFlux] [bit] NULL,
	[z_flagBadModelFlux] [bit] NULL,
	[z_flagBadInstFlux] [bit] NULL,
	[z_flagBadCentroid] [bit] NULL,
	[z_flagBadShape] [bit] NULL,
	[y_psfFlux] [float] NULL,
	[y_psfFluxSigma] [float] NULL,
	[y_apFlux] [float] NULL,
	[y_apFluxSigma] [float] NULL,
	[y_modelFlux] [float] NULL,
	[y_modelFluxSigma] [float] NULL,
	[y_instFlux] [float] NULL,
	[y_instFluxSigma] [float] NULL,
	[y_apCorrection] [float] NULL,
	[y_apCorrectionSigma] [float] NULL,
	[y_shapeIx] [float] NULL,
	[y_shapeIy] [float] NULL,
	[y_shapeIxVar] [float] NULL,
	[y_shapeIyVar] [float] NULL,
	[y_shapeIxIyCov] [float] NULL,
	[y_shapeIxx] [float] NULL,
	[y_shapeIyy] [float] NULL,
	[y_shapeIxy] [float] NULL,
	[y_shapeIxxVar] [float] NULL,
	[y_shapeIyyVar] [float] NULL,
	[y_shapeIxyVar] [float] NULL,
	[y_shapeIxxIyyCov] [float] NULL,
	[y_shapeIxxIxyCov] [float] NULL,
	[y_shapeIyyIxyCov] [float] NULL,
	[y_extendedness] [float] NULL,
	[y_flagNegative] [bit] NULL,
	[y_flagBadMeasCentroid] [bit] NULL,
	[y_flagPixEdge] [bit] NULL,
	[y_flagPixInterpAny] [bit] NULL,
	[y_flagPixInterpCen] [bit] NULL,
	[y_flagPixSaturAny] [bit] NULL,
	[y_flagPixSaturCen] [bit] NULL,
	[y_flagBadPsfFlux] [bit] NULL,
	[y_flagBadApFlux] [bit] NULL,
	[y_flagBadModelFlux] [bit] NULL,
	[y_flagBadInstFlux] [bit] NULL,
	[y_flagBadCentroid] [bit] NULL,
	[y_flagBadShape] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[deepSourceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION=PAGE) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ObjectFullOverlap_1025](
	[deepSourceId] [bigint] NOT NULL,
	[ra] [float] NOT NULL,
	[decl] [float] NOT NULL,
	[raVar] [float] NULL,
	[declVar] [float] NULL,
	[radeclCov] [float] NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL,
	[u_psfFlux] [float] NULL,
	[u_psfFluxSigma] [float] NULL,
	[u_apFlux] [float] NULL,
	[u_apFluxSigma] [float] NULL,
	[u_modelFlux] [float] NULL,
	[u_modelFluxSigma] [float] NULL,
	[u_instFlux] [float] NULL,
	[u_instFluxSigma] [float] NULL,
	[u_apCorrection] [float] NULL,
	[u_apCorrectionSigma] [float] NULL,
	[u_shapeIx] [float] NULL,
	[u_shapeIy] [float] NULL,
	[u_shapeIxVar] [float] NULL,
	[u_shapeIyVar] [float] NULL,
	[u_shapeIxIyCov] [float] NULL,
	[u_shapeIxx] [float] NULL,
	[u_shapeIyy] [float] NULL,
	[u_shapeIxy] [float] NULL,
	[u_shapeIxxVar] [float] NULL,
	[u_shapeIyyVar] [float] NULL,
	[u_shapeIxyVar] [float] NULL,
	[u_shapeIxxIyyCov] [float] NULL,
	[u_shapeIxxIxyCov] [float] NULL,
	[u_shapeIyyIxyCov] [float] NULL,
	[u_extendedness] [float] NULL,
	[u_flagNegative] [bit] NULL,
	[u_flagBadMeasCentroid] [bit] NULL,
	[u_flagPixEdge] [bit] NULL,
	[u_flagPixInterpAny] [bit] NULL,
	[u_flagPixInterpCen] [bit] NULL,
	[u_flagPixSaturAny] [bit] NULL,
	[u_flagPixSaturCen] [bit] NULL,
	[u_flagBadPsfFlux] [bit] NULL,
	[u_flagBadApFlux] [bit] NULL,
	[u_flagBadModelFlux] [bit] NULL,
	[u_flagBadInstFlux] [bit] NULL,
	[u_flagBadCentroid] [bit] NULL,
	[u_flagBadShape] [bit] NULL,
	[g_psfFlux] [float] NULL,
	[g_psfFluxSigma] [float] NULL,
	[g_apFlux] [float] NULL,
	[g_apFluxSigma] [float] NULL,
	[g_modelFlux] [float] NULL,
	[g_modelFluxSigma] [float] NULL,
	[g_instFlux] [float] NULL,
	[g_instFluxSigma] [float] NULL,
	[g_apCorrection] [float] NULL,
	[g_apCorrectionSigma] [float] NULL,
	[g_shapeIx] [float] NULL,
	[g_shapeIy] [float] NULL,
	[g_shapeIxVar] [float] NULL,
	[g_shapeIyVar] [float] NULL,
	[g_shapeIxIyCov] [float] NULL,
	[g_shapeIxx] [float] NULL,
	[g_shapeIyy] [float] NULL,
	[g_shapeIxy] [float] NULL,
	[g_shapeIxxVar] [float] NULL,
	[g_shapeIyyVar] [float] NULL,
	[g_shapeIxyVar] [float] NULL,
	[g_shapeIxxIyyCov] [float] NULL,
	[g_shapeIxxIxyCov] [float] NULL,
	[g_shapeIyyIxyCov] [float] NULL,
	[g_extendedness] [float] NULL,
	[g_flagNegative] [bit] NULL,
	[g_flagBadMeasCentroid] [bit] NULL,
	[g_flagPixEdge] [bit] NULL,
	[g_flagPixInterpAny] [bit] NULL,
	[g_flagPixInterpCen] [bit] NULL,
	[g_flagPixSaturAny] [bit] NULL,
	[g_flagPixSaturCen] [bit] NULL,
	[g_flagBadPsfFlux] [bit] NULL,
	[g_flagBadApFlux] [bit] NULL,
	[g_flagBadModelFlux] [bit] NULL,
	[g_flagBadInstFlux] [bit] NULL,
	[g_flagBadCentroid] [bit] NULL,
	[g_flagBadShape] [bit] NULL,
	[r_psfFlux] [float] NULL,
	[r_psfFluxSigma] [float] NULL,
	[r_apFlux] [float] NULL,
	[r_apFluxSigma] [float] NULL,
	[r_modelFlux] [float] NULL,
	[r_modelFluxSigma] [float] NULL,
	[r_instFlux] [float] NULL,
	[r_instFluxSigma] [float] NULL,
	[r_apCorrection] [float] NULL,
	[r_apCorrectionSigma] [float] NULL,
	[r_shapeIx] [float] NULL,
	[r_shapeIy] [float] NULL,
	[r_shapeIxVar] [float] NULL,
	[r_shapeIyVar] [float] NULL,
	[r_shapeIxIyCov] [float] NULL,
	[r_shapeIxx] [float] NULL,
	[r_shapeIyy] [float] NULL,
	[r_shapeIxy] [float] NULL,
	[r_shapeIxxVar] [float] NULL,
	[r_shapeIyyVar] [float] NULL,
	[r_shapeIxyVar] [float] NULL,
	[r_shapeIxxIyyCov] [float] NULL,
	[r_shapeIxxIxyCov] [float] NULL,
	[r_shapeIyyIxyCov] [float] NULL,
	[r_extendedness] [float] NULL,
	[r_flagNegative] [bit] NULL,
	[r_flagBadMeasCentroid] [bit] NULL,
	[r_flagPixEdge] [bit] NULL,
	[r_flagPixInterpAny] [bit] NULL,
	[r_flagPixInterpCen] [bit] NULL,
	[r_flagPixSaturAny] [bit] NULL,
	[r_flagPixSaturCen] [bit] NULL,
	[r_flagBadPsfFlux] [bit] NULL,
	[r_flagBadApFlux] [bit] NULL,
	[r_flagBadModelFlux] [bit] NULL,
	[r_flagBadInstFlux] [bit] NULL,
	[r_flagBadCentroid] [bit] NULL,
	[r_flagBadShape] [bit] NULL,
	[i_psfFlux] [float] NULL,
	[i_psfFluxSigma] [float] NULL,
	[i_apFlux] [float] NULL,
	[i_apFluxSigma] [float] NULL,
	[i_modelFlux] [float] NULL,
	[i_modelFluxSigma] [float] NULL,
	[i_instFlux] [float] NULL,
	[i_instFluxSigma] [float] NULL,
	[i_apCorrection] [float] NULL,
	[i_apCorrectionSigma] [float] NULL,
	[i_shapeIx] [float] NULL,
	[i_shapeIy] [float] NULL,
	[i_shapeIxVar] [float] NULL,
	[i_shapeIyVar] [float] NULL,
	[i_shapeIxIyCov] [float] NULL,
	[i_shapeIxx] [float] NULL,
	[i_shapeIyy] [float] NULL,
	[i_shapeIxy] [float] NULL,
	[i_shapeIxxVar] [float] NULL,
	[i_shapeIyyVar] [float] NULL,
	[i_shapeIxyVar] [float] NULL,
	[i_shapeIxxIyyCov] [float] NULL,
	[i_shapeIxxIxyCov] [float] NULL,
	[i_shapeIyyIxyCov] [float] NULL,
	[i_extendedness] [float] NULL,
	[i_flagNegative] [bit] NULL,
	[i_flagBadMeasCentroid] [bit] NULL,
	[i_flagPixEdge] [bit] NULL,
	[i_flagPixInterpAny] [bit] NULL,
	[i_flagPixInterpCen] [bit] NULL,
	[i_flagPixSaturAny] [bit] NULL,
	[i_flagPixSaturCen] [bit] NULL,
	[i_flagBadPsfFlux] [bit] NULL,
	[i_flagBadApFlux] [bit] NULL,
	[i_flagBadModelFlux] [bit] NULL,
	[i_flagBadInstFlux] [bit] NULL,
	[i_flagBadCentroid] [bit] NULL,
	[i_flagBadShape] [bit] NULL,
	[z_psfFlux] [float] NULL,
	[z_psfFluxSigma] [float] NULL,
	[z_apFlux] [float] NULL,
	[z_apFluxSigma] [float] NULL,
	[z_modelFlux] [float] NULL,
	[z_modelFluxSigma] [float] NULL,
	[z_instFlux] [float] NULL,
	[z_instFluxSigma] [float] NULL,
	[z_apCorrection] [float] NULL,
	[z_apCorrectionSigma] [float] NULL,
	[z_shapeIx] [float] NULL,
	[z_shapeIy] [float] NULL,
	[z_shapeIxVar] [float] NULL,
	[z_shapeIyVar] [float] NULL,
	[z_shapeIxIyCov] [float] NULL,
	[z_shapeIxx] [float] NULL,
	[z_shapeIyy] [float] NULL,
	[z_shapeIxy] [float] NULL,
	[z_shapeIxxVar] [float] NULL,
	[z_shapeIyyVar] [float] NULL,
	[z_shapeIxyVar] [float] NULL,
	[z_shapeIxxIyyCov] [float] NULL,
	[z_shapeIxxIxyCov] [float] NULL,
	[z_shapeIyyIxyCov] [float] NULL,
	[z_extendedness] [float] NULL,
	[z_flagNegative] [bit] NULL,
	[z_flagBadMeasCentroid] [bit] NULL,
	[z_flagPixEdge] [bit] NULL,
	[z_flagPixInterpAny] [bit] NULL,
	[z_flagPixInterpCen] [bit] NULL,
	[z_flagPixSaturAny] [bit] NULL,
	[z_flagPixSaturCen] [bit] NULL,
	[z_flagBadPsfFlux] [bit] NULL,
	[z_flagBadApFlux] [bit] NULL,
	[z_flagBadModelFlux] [bit] NULL,
	[z_flagBadInstFlux] [bit] NULL,
	[z_flagBadCentroid] [bit] NULL,
	[z_flagBadShape] [bit] NULL,
	[y_psfFlux] [float] NULL,
	[y_psfFluxSigma] [float] NULL,
	[y_apFlux] [float] NULL,
	[y_apFluxSigma] [float] NULL,
	[y_modelFlux] [float] NULL,
	[y_modelFluxSigma] [float] NULL,
	[y_instFlux] [float] NULL,
	[y_instFluxSigma] [float] NULL,
	[y_apCorrection] [float] NULL,
	[y_apCorrectionSigma] [float] NULL,
	[y_shapeIx] [float] NULL,
	[y_shapeIy] [float] NULL,
	[y_shapeIxVar] [float] NULL,
	[y_shapeIyVar] [float] NULL,
	[y_shapeIxIyCov] [float] NULL,
	[y_shapeIxx] [float] NULL,
	[y_shapeIyy] [float] NULL,
	[y_shapeIxy] [float] NULL,
	[y_shapeIxxVar] [float] NULL,
	[y_shapeIyyVar] [float] NULL,
	[y_shapeIxyVar] [float] NULL,
	[y_shapeIxxIyyCov] [float] NULL,
	[y_shapeIxxIxyCov] [float] NULL,
	[y_shapeIyyIxyCov] [float] NULL,
	[y_extendedness] [float] NULL,
	[y_flagNegative] [bit] NULL,
	[y_flagBadMeasCentroid] [bit] NULL,
	[y_flagPixEdge] [bit] NULL,
	[y_flagPixInterpAny] [bit] NULL,
	[y_flagPixInterpCen] [bit] NULL,
	[y_flagPixSaturAny] [bit] NULL,
	[y_flagPixSaturCen] [bit] NULL,
	[y_flagBadPsfFlux] [bit] NULL,
	[y_flagBadApFlux] [bit] NULL,
	[y_flagBadModelFlux] [bit] NULL,
	[y_flagBadInstFlux] [bit] NULL,
	[y_flagBadCentroid] [bit] NULL,
	[y_flagBadShape] [bit] NULL
) ON [PRIMARY]

GO
CREATE CLUSTERED INDEX [idx_objflolap_1025_dpsrcid] ON [dbo].[ObjectFullOverlap_1025]
(
	[deepSourceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION=PAGE) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Source_1025](
	[id] [bigint] NOT NULL,
	[coord_ra] [float] NULL,
	[coord_decl] [float] NULL,
	[coord_htmId20] [bigint] NULL,
	[parent] [bigint] NULL,
	[flags_badcentroid] [bit] NOT NULL,
	[centroid_sdss_x] [float] NULL,
	[centroid_sdss_y] [float] NULL,
	[centroid_sdss_xVar] [float] NULL,
	[centroid_sdss_xyCov] [float] NULL,
	[centroid_sdss_yVar] [float] NULL,
	[centroid_sdss_flags] [bit] NOT NULL,
	[flags_pixel_edge] [bit] NOT NULL,
	[flags_pixel_interpolated_any] [bit] NOT NULL,
	[flags_pixel_interpolated_center] [bit] NOT NULL,
	[flags_pixel_saturated_any] [bit] NOT NULL,
	[flags_pixel_saturated_center] [bit] NOT NULL,
	[flags_pixel_cr_any] [bit] NOT NULL,
	[flags_pixel_cr_center] [bit] NOT NULL,
	[centroid_naive_x] [float] NULL,
	[centroid_naive_y] [float] NULL,
	[centroid_naive_xVar] [float] NULL,
	[centroid_naive_xyCov] [float] NULL,
	[centroid_naive_yVar] [float] NULL,
	[centroid_naive_flags] [bit] NOT NULL,
	[centroid_gaussian_x] [float] NULL,
	[centroid_gaussian_y] [float] NULL,
	[centroid_gaussian_xVar] [float] NULL,
	[centroid_gaussian_xyCov] [float] NULL,
	[centroid_gaussian_yVar] [float] NULL,
	[centroid_gaussian_flags] [bit] NOT NULL,
	[shape_sdss_Ixx] [float] NULL,
	[shape_sdss_Iyy] [float] NULL,
	[shape_sdss_Ixy] [float] NULL,
	[shape_sdss_IxxVar] [float] NULL,
	[shape_sdss_IxxIyyCov] [float] NULL,
	[shape_sdss_IxxIxyCov] [float] NULL,
	[shape_sdss_IyyVar] [float] NULL,
	[shape_sdss_IyyIxyCov] [float] NULL,
	[shape_sdss_IxyVar] [float] NULL,
	[shape_sdss_flags] [bit] NOT NULL,
	[shape_sdss_centroid_x] [float] NULL,
	[shape_sdss_centroid_y] [float] NULL,
	[shape_sdss_centroid_xVar] [float] NULL,
	[shape_sdss_centroid_xyCov] [float] NULL,
	[shape_sdss_centroid_yVar] [float] NULL,
	[shape_sdss_centroid_flags] [bit] NOT NULL,
	[shape_sdss_flags_unweightedbad] [bit] NOT NULL,
	[shape_sdss_flags_unweighted] [bit] NOT NULL,
	[shape_sdss_flags_shift] [bit] NOT NULL,
	[shape_sdss_flags_maxiter] [bit] NOT NULL,
	[flux_psf] [float] NULL,
	[flux_psf_err] [float] NULL,
	[flux_psf_flags] [bit] NOT NULL,
	[flux_psf_psffactor] [real] NULL,
	[flux_psf_flags_psffactor] [bit] NOT NULL,
	[flux_psf_flags_badcorr] [bit] NOT NULL,
	[flux_naive] [float] NULL,
	[flux_naive_err] [float] NULL,
	[flux_naive_flags] [bit] NOT NULL,
	[flux_gaussian] [float] NULL,
	[flux_gaussian_err] [float] NULL,
	[flux_gaussian_flags] [bit] NOT NULL,
	[flux_gaussian_psffactor] [real] NULL,
	[flux_gaussian_flags_psffactor] [bit] NOT NULL,
	[flux_gaussian_flags_badcorr] [bit] NOT NULL,
	[flux_sinc] [float] NULL,
	[flux_sinc_err] [float] NULL,
	[flux_sinc_flags] [bit] NOT NULL,
	[centroid_record_x] [float] NULL,
	[centroid_record_y] [float] NULL,
	[classification_extendedness] [float] NULL,
	[aperturecorrection] [float] NULL,
	[aperturecorrection_err] [float] NULL,
	[refFlux] [float] NULL,
	[refFlux_err] [float] NULL,
	[objectId] [bigint] NOT NULL,
	[coord_raVar] [float] NULL,
	[coord_radeclCov] [float] NULL,
	[coord_declVar] [float] NULL,
	[exposure_id] [bigint] NOT NULL,
	[exposure_filter_id] [int] NOT NULL,
	[exposure_time] [real] NULL,
	[exposure_time_mid] [float] NULL,
	[cluster_id] [bigint] NULL,
	[cluster_coord_ra] [float] NULL,
	[cluster_coord_decl] [float] NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION=PAGE) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SourceFullOverlap_1025](
	[id] [bigint] NOT NULL,
	[coord_ra] [float] NULL,
	[coord_decl] [float] NULL,
	[coord_htmId20] [bigint] NULL,
	[parent] [bigint] NULL,
	[flags_badcentroid] [bit] NOT NULL,
	[centroid_sdss_x] [float] NULL,
	[centroid_sdss_y] [float] NULL,
	[centroid_sdss_xVar] [float] NULL,
	[centroid_sdss_xyCov] [float] NULL,
	[centroid_sdss_yVar] [float] NULL,
	[centroid_sdss_flags] [bit] NOT NULL,
	[flags_pixel_edge] [bit] NOT NULL,
	[flags_pixel_interpolated_any] [bit] NOT NULL,
	[flags_pixel_interpolated_center] [bit] NOT NULL,
	[flags_pixel_saturated_any] [bit] NOT NULL,
	[flags_pixel_saturated_center] [bit] NOT NULL,
	[flags_pixel_cr_any] [bit] NOT NULL,
	[flags_pixel_cr_center] [bit] NOT NULL,
	[centroid_naive_x] [float] NULL,
	[centroid_naive_y] [float] NULL,
	[centroid_naive_xVar] [float] NULL,
	[centroid_naive_xyCov] [float] NULL,
	[centroid_naive_yVar] [float] NULL,
	[centroid_naive_flags] [bit] NOT NULL,
	[centroid_gaussian_x] [float] NULL,
	[centroid_gaussian_y] [float] NULL,
	[centroid_gaussian_xVar] [float] NULL,
	[centroid_gaussian_xyCov] [float] NULL,
	[centroid_gaussian_yVar] [float] NULL,
	[centroid_gaussian_flags] [bit] NOT NULL,
	[shape_sdss_Ixx] [float] NULL,
	[shape_sdss_Iyy] [float] NULL,
	[shape_sdss_Ixy] [float] NULL,
	[shape_sdss_IxxVar] [float] NULL,
	[shape_sdss_IxxIyyCov] [float] NULL,
	[shape_sdss_IxxIxyCov] [float] NULL,
	[shape_sdss_IyyVar] [float] NULL,
	[shape_sdss_IyyIxyCov] [float] NULL,
	[shape_sdss_IxyVar] [float] NULL,
	[shape_sdss_flags] [bit] NOT NULL,
	[shape_sdss_centroid_x] [float] NULL,
	[shape_sdss_centroid_y] [float] NULL,
	[shape_sdss_centroid_xVar] [float] NULL,
	[shape_sdss_centroid_xyCov] [float] NULL,
	[shape_sdss_centroid_yVar] [float] NULL,
	[shape_sdss_centroid_flags] [bit] NOT NULL,
	[shape_sdss_flags_unweightedbad] [bit] NOT NULL,
	[shape_sdss_flags_unweighted] [bit] NOT NULL,
	[shape_sdss_flags_shift] [bit] NOT NULL,
	[shape_sdss_flags_maxiter] [bit] NOT NULL,
	[flux_psf] [float] NULL,
	[flux_psf_err] [float] NULL,
	[flux_psf_flags] [bit] NOT NULL,
	[flux_psf_psffactor] [real] NULL,
	[flux_psf_flags_psffactor] [bit] NOT NULL,
	[flux_psf_flags_badcorr] [bit] NOT NULL,
	[flux_naive] [float] NULL,
	[flux_naive_err] [float] NULL,
	[flux_naive_flags] [bit] NOT NULL,
	[flux_gaussian] [float] NULL,
	[flux_gaussian_err] [float] NULL,
	[flux_gaussian_flags] [bit] NOT NULL,
	[flux_gaussian_psffactor] [real] NULL,
	[flux_gaussian_flags_psffactor] [bit] NOT NULL,
	[flux_gaussian_flags_badcorr] [bit] NOT NULL,
	[flux_sinc] [float] NULL,
	[flux_sinc_err] [float] NULL,
	[flux_sinc_flags] [bit] NOT NULL,
	[centroid_record_x] [float] NULL,
	[centroid_record_y] [float] NULL,
	[classification_extendedness] [float] NULL,
	[aperturecorrection] [float] NULL,
	[aperturecorrection_err] [float] NULL,
	[refFlux] [float] NULL,
	[refFlux_err] [float] NULL,
	[objectId] [bigint] NOT NULL,
	[coord_raVar] [float] NULL,
	[coord_radeclCov] [float] NULL,
	[coord_declVar] [float] NULL,
	[exposure_id] [bigint] NOT NULL,
	[exposure_filter_id] [int] NOT NULL,
	[exposure_time] [real] NULL,
	[exposure_time_mid] [float] NULL,
	[cluster_id] [bigint] NULL,
	[cluster_coord_ra] [float] NULL,
	[cluster_coord_decl] [float] NULL,
	[chunkId] [int] NOT NULL,
	[subChunkId] [int] NOT NULL
) ON [PRIMARY]

GO
CREATE CLUSTERED INDEX [idx_srcflolap_1025_id] ON [dbo].[SourceFullOverlap_1025]
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,DATA_COMPRESSION=PAGE) ON [PRIMARY]
GO