apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    MSSQL_CLUSTER: filedb
  name: master
  namespace: filedb
  selfLink: /apis/apps/v1/namespaces/filedb/statefulsets/master
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      MSSQL_CLUSTER: filedb
      app: master
      plane: data
      role: master-pool
  serviceName: master-svc
  template:
    metadata:
      annotations:
        microsoft.com/ignore-container-health: mssql-mlservices-rserver;mssql-mlservices-pythonserver;mssql-java
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedb
        app: master
        plane: data
        role: master-pool
    spec:
      containers:
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: hadoop
        - name: MSSQL_AGENT_PORT
          value: "8300"
        - name: HADOOP_HEAPSIZE
          value: "2048"
        - name: YARN_HEAPSIZE
          value: "2048"
        - name: YARN_SCHEDULER_MAX_MEMORY
          value: "655360"
        - name: YARN_SCHEDULER_MAX_VCORES
          value: "300"
        - name: YARN_NODEMANAGER_RESOURCE_MEMORY
          value: "65536"
        - name: YARN_NODEMANAGER_RESOURCE_VCORES
          value: "30"
        - name: YARN_SCHEDULER_CAPACITY_MAX_AM_PERCENT
          value: "0.3"
        - name: SPARK_DRIVER_MEMORY
          value: 2g
        - name: SPARK_DRIVER_CORES
          value: "1"
        - name: SPARK_EXECUTOR_INSTANCES
          value: "11"
        - name: SPARK_EXECUTOR_MEMORY
          value: 12g
        - name: SPARK_EXECUTOR_CORES
          value: "10"
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-hadoop:ctp3.0
        imagePullPolicy: Always
        name: hadoop
        ports:
        - containerPort: 8088
          name: port-8088
          protocol: TCP
        - containerPort: 50075
          name: port-50075
          protocol: TCP
        - containerPort: 50020
          name: port-50020
          protocol: TCP
        - containerPort: 50010
          name: port-50010
          protocol: TCP
        - containerPort: 8030
          name: port-8030
          protocol: TCP
        - containerPort: 8031
          name: port-8031
          protocol: TCP
        - containerPort: 8032
          name: port-8032
          protocol: TCP
        - containerPort: 8033
          name: port-8033
          protocol: TCP
        - containerPort: 8040
          name: port-8040
          protocol: TCP
        - containerPort: 8042
          name: port-8042
          protocol: TCP
        - containerPort: 8998
          name: port-8998
          protocol: TCP
        - containerPort: 8300
          name: agent-port-8300
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /var/opt
          name: data
          subPath: hadoop
        - mountPath: /root/hdfs/namenode
          name: data
          subPath: namenode
        - mountPath: /opt/mssql/mlservices
          name: data
          subPath: shared/mlservices
        - mountPath: /opt/mssql/mssql-java
          name: data
          subPath: shared/java
        - mountPath: /usr/local/hadoop/logs
          name: logs
          subPath: hadoop/hadoop
        - mountPath: /var/log
          name: logs
          subPath: hadoop
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-server
        - name: MSSQL_AGENT_PORT
          value: "8301"
        - name: ACCEPT_EULA
          value: "Y"
        - name: ACCEPT_EULA_ML
          value: "Y"
        - name: MSSQL_RPC_PORT
          value: "135"
        - name: MSSQL_DTC_TCP_PORT
          value: "51000"
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-server-data:ctp3.0
        imagePullPolicy: Always
        name: mssql-server
        ports:
        - containerPort: 135
          name: rpc-port-135
          protocol: TCP
        - containerPort: 1433
          name: port-1433
          protocol: TCP
        - containerPort: 8301
          name: agent-port-8301
          protocol: TCP
        - containerPort: 51000
          name: dtc-port-51000
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /var/run/container.ready
          failureThreshold: 210
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /root/secrets/node-admin-login
          name: node-admin-login-secrets
          readOnly: true
        - mountPath: /var/opt
          name: data
          subPath: mssql-server
        - mountPath: /opt/mssql/mlservices
          name: data
          subPath: shared/mlservices
        - mountPath: /opt/mssql/java
          name: data
          subPath: shared/java
        - mountPath: /var/log
          name: logs
          subPath: mssql-server
      - env:
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-mlservices-rserver
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-mlservices-rserver:ctp3.0
        imagePullPolicy: Always
        name: mssql-mlservices-rserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/mlservices
          name: data
          subPath: shared/mlservices
      - env:
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-mlservices-pythonserver
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-mlservices-pythonserver:ctp3.0
        imagePullPolicy: Always
        name: mssql-mlservices-pythonserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/mlservices
          name: data
          subPath: shared/mlservices
      - env:
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-java
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-java:ctp3.0
        imagePullPolicy: Always
        name: mssql-java
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/java
          name: data
          subPath: shared/java
      - env:
        - name: MONITORING_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_AGENT_PORT
          value: "8310"
        - name: INFLUX_DB_SERVER
          value: metricsdb-svc
        - name: INFLUX_DB_PORT
          value: "25826"
        - name: SQL_HOSTNAME
          value: 127.0.0.1
        - name: SQL_POLL_INTERVAL
          value: "5"
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: collectd
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-collectd:ctp3.0
        imagePullPolicy: Always
        name: collectd
        ports:
        - containerPort: 8310
          name: agent-port-8310
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /var/opt
          name: data
          subPath: collectd
        - mountPath: /var/log
          name: logs
          subPath: collectd
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: logsdb-svc
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENTBIT_CONFIG
          value: fluentbit-master-pool.conf
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MSSQL_POD_TYPE
          value: master
        - name: MSSQL_CONTAINER_TYPE
          value: fluentbit
        - name: MSSQL_POD_KIND
          value: StatefulSet
        - name: MSSQL_AGENT_PORT
          value: "8311"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-fluentbit:ctp3.0
        imagePullPolicy: Always
        name: fluentbit
        ports:
        - containerPort: 2020
          name: fluentb-2020
          protocol: TCP
        - containerPort: 8311
          name: agent-port-8311
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /var/opt
          name: data
        - mountPath: /var/log
          name: logs
          subPath: fluentbit
        - mountPath: /mnt/logs
          name: logs
          readOnly: true
      dnsConfig:
        searches:
        - data-0-svc.filedb.svc.cluster.local
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mssql-private-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: mssql-master-pool-secret
        secret:
          defaultMode: 420
          secretName: mssql-master-pool-secret
      - name: node-admin-login-secrets
        secret:
          defaultMode: 420
          secretName: node-admin-login-secret
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 15Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0
