apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    MSSQL_CLUSTER: filedb
  name: nmnode-0
  selfLink: /apis/apps/v1/namespaces/filedb/statefulsets/nmnode-0
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      MSSQL_CLUSTER: filedb
      app: nmnode-0
      plane: data
      pool-name: default
      pool-number: "0"
      role: namenode
  serviceName: nmnode-0-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedb
        app: nmnode-0
        plane: data
        pool-name: default
        pool-number: "0"
        role: namenode
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nmnode-0
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: nmnode
        - name: MSSQL_CONTAINER_TYPE
          value: hadoop
        - name: MSSQL_AGENT_PORT
          value: "8300"
        - name: HADOOP_HEAPSIZE
          value: "2048"
        - name: MSSQL_POD_KIND
          value: StatefulSet
        image: mcr.microsoft.com/mssql/bdc/mssql-hadoop:2019-CTP3.2-ubuntu
        imagePullPolicy: Always
        name: hadoop
        ports:
        - containerPort: 9000
          name: default-fs
          protocol: TCP
        - containerPort: 50070
          name: name-node-http
          protocol: TCP
        - containerPort: 50470
          name: name-node-https
          protocol: TCP
        - containerPort: 14000
          name: http-fs
          protocol: TCP
        - containerPort: 8300
          name: agent-port-8300
          protocol: TCP
        - containerPort: 50200
          name: tiering-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /var/run/secrets/credentials/pool
          name: mssql-master-pool-secret
          readOnly: true
        - mountPath: /var/run/secrets/credentials/controller-internal
          name: controller-internal-secret
          readOnly: true
        - mountPath: /var/opt
          name: data
          subPath: hadoop/var/opt
        - mountPath: /var/opt/hdfs/namenode
          name: data
          subPath: hadoop/namenode
        - mountPath: /var/run/configmaps/cluster
          name: cluster-config-volume
        - mountPath: /var/log
          name: logs
          subPath: hadoop
        - mountPath: /var/run
          name: var-run
          subPath: hadoop
        - mountPath: /var/run/configmaps/hadoop
          name: hadoop-config-volume
          readOnly: true
        - mountPath: /var/run/secrets/certificates/agent
          name: nmnode-0-agent-secret
          readOnly: true
      dnsConfig:
        options:
        - name: timeout
          value: "30"
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: mssql-private-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mssql-master-pool-secret
        secret:
          defaultMode: 420
          secretName: mssql-master-pool-secret
      - name: controller-internal-secret
        secret:
          defaultMode: 420
          secretName: controller-internal-secret
      - emptyDir:
          medium: Memory
        name: var-run
      - configMap:
          defaultMode: 420
          name: mssql-hadoop-storage-0-configmap
        name: hadoop-config-volume
      - name: nmnode-0-agent-secret
        secret:
          defaultMode: 420
          secretName: nmnode-0-agent-secret
      - configMap:
          defaultMode: 420
          name: cluster-configmap
        name: cluster-config-volume
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 15Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0
