--create database LSST

USE LSST
GO



--drop external table objectDP_rep
--based on Sue's https://github.com/idies/jhu-lsst/blob/master/mysql/mssql-createTables.sql
CREATE EXTERNAL TABLE ObjectDP_rep (
	[deepSourceId] BIGINT NULL,
	[ra] FLOAT NOT NULL,
	[decl] FLOAT NOT NULL,
	[raVar] FLOAT NULL ,
	[declVar] FLOAT NULL ,
	[radeclCov] FLOAT NULL ,
	[chunkId] INT NOT NULL,
	[subChunkId] INT NOT NULL,
	[u_psfFlux] FLOAT NULL ,
	[u_psfFluxSigma] FLOAT NULL ,
	[u_apFlux] FLOAT NULL ,
	[u_apFluxSigma] FLOAT NULL ,
	[u_modelFlux] FLOAT NULL ,
	[u_modelFluxSigma] FLOAT NULL ,
	[u_instFlux] FLOAT NULL ,
	[u_instFluxSigma] FLOAT NULL ,
	[u_apCorrection] FLOAT NULL ,
	[u_apCorrectionSigma] FLOAT NULL ,
	[u_shapeIx] FLOAT NULL ,
	[u_shapeIy] FLOAT NULL ,
	[u_shapeIxVar] FLOAT NULL ,
	[u_shapeIyVar] FLOAT NULL ,
	[u_shapeIxIyCov] FLOAT NULL ,
	[u_shapeIxx] FLOAT NULL ,
	[u_shapeIyy] FLOAT NULL ,
	[u_shapeIxy] FLOAT NULL ,
	[u_shapeIxxVar] FLOAT NULL ,
	[u_shapeIyyVar] FLOAT NULL ,
	[u_shapeIxyVar] FLOAT NULL ,
	[u_shapeIxxIyyCov] FLOAT NULL ,
	[u_shapeIxxIxyCov] FLOAT NULL ,
	[u_shapeIyyIxyCov] FLOAT NULL ,
	[u_extendedness] FLOAT NULL ,
	[u_flagNegative] INT NULL ,
	[u_flagBadMeasCentroid] INT NULL ,
	[u_flagPixEdge] INT NULL ,
	[u_flagPixInterpAny] INT NULL ,
	[u_flagPixInterpCen] INT NULL ,
	[u_flagPixSaturAny] INT NULL ,
	[u_flagPixSaturCen] INT NULL ,
	[u_flagBadPsfFlux] INT NULL ,
	[u_flagBadApFlux] INT NULL ,
	[u_flagBadModelFlux] INT NULL ,
	[u_flagBadInstFlux] INT NULL ,
	[u_flagBadCentroid] INT NULL ,
	[u_flagBadShape] INT NULL ,
	[g_psfFlux] FLOAT NULL ,
	[g_psfFluxSigma] FLOAT NULL ,
	[g_apFlux] FLOAT NULL ,
	[g_apFluxSigma] FLOAT NULL ,
	[g_modelFlux] FLOAT NULL ,
	[g_modelFluxSigma] FLOAT NULL ,
	[g_instFlux] FLOAT NULL ,
	[g_instFluxSigma] FLOAT NULL ,
	[g_apCorrection] FLOAT NULL ,
	[g_apCorrectionSigma] FLOAT NULL ,
	[g_shapeIx] FLOAT NULL ,
	[g_shapeIy] FLOAT NULL ,
	[g_shapeIxVar] FLOAT NULL ,
	[g_shapeIyVar] FLOAT NULL ,
	[g_shapeIxIyCov] FLOAT NULL ,
	[g_shapeIxx] FLOAT NULL ,
	[g_shapeIyy] FLOAT NULL ,
	[g_shapeIxy] FLOAT NULL ,
	[g_shapeIxxVar] FLOAT NULL ,
	[g_shapeIyyVar] FLOAT NULL ,
	[g_shapeIxyVar] FLOAT NULL ,
	[g_shapeIxxIyyCov] FLOAT NULL ,
	[g_shapeIxxIxyCov] FLOAT NULL ,
	[g_shapeIyyIxyCov] FLOAT NULL ,
	[g_extendedness] FLOAT NULL ,
	[g_flagNegative] INT NULL ,
	[g_flagBadMeasCentroid] INT NULL ,
	[g_flagPixEdge] INT NULL ,
	[g_flagPixInterpAny] INT NULL ,
	[g_flagPixInterpCen] INT NULL ,
	[g_flagPixSaturAny] INT NULL ,
	[g_flagPixSaturCen] INT NULL ,
	[g_flagBadPsfFlux] INT NULL ,
	[g_flagBadApFlux] INT NULL ,
	[g_flagBadModelFlux] INT NULL ,
	[g_flagBadInstFlux] INT NULL ,
	[g_flagBadCentroid] INT NULL ,
	[g_flagBadShape] INT NULL ,
	[r_psfFlux] FLOAT NULL ,
	[r_psfFluxSigma] FLOAT NULL ,
	[r_apFlux] FLOAT NULL ,
	[r_apFluxSigma] FLOAT NULL ,
	[r_modelFlux] FLOAT NULL ,
	[r_modelFluxSigma] FLOAT NULL ,
	[r_instFlux] FLOAT NULL ,
	[r_instFluxSigma] FLOAT NULL ,
	[r_apCorrection] FLOAT NULL ,
	[r_apCorrectionSigma] FLOAT NULL ,
	[r_shapeIx] FLOAT NULL ,
	[r_shapeIy] FLOAT NULL ,
	[r_shapeIxVar] FLOAT NULL ,
	[r_shapeIyVar] FLOAT NULL ,
	[r_shapeIxIyCov] FLOAT NULL ,
	[r_shapeIxx] FLOAT NULL ,
	[r_shapeIyy] FLOAT NULL ,
	[r_shapeIxy] FLOAT NULL ,
	[r_shapeIxxVar] FLOAT NULL ,
	[r_shapeIyyVar] FLOAT NULL ,
	[r_shapeIxyVar] FLOAT NULL ,
	[r_shapeIxxIyyCov] FLOAT NULL ,
	[r_shapeIxxIxyCov] FLOAT NULL ,
	[r_shapeIyyIxyCov] FLOAT NULL ,
	[r_extendedness] FLOAT NULL ,
	[r_flagNegative] INT NULL ,
	[r_flagBadMeasCentroid] INT NULL ,
	[r_flagPixEdge] INT NULL ,
	[r_flagPixInterpAny] INT NULL ,
	[r_flagPixInterpCen] INT NULL ,
	[r_flagPixSaturAny] INT NULL ,
	[r_flagPixSaturCen] INT NULL ,
	[r_flagBadPsfFlux] INT NULL ,
	[r_flagBadApFlux] INT NULL ,
	[r_flagBadModelFlux] INT NULL ,
	[r_flagBadInstFlux] INT NULL ,
	[r_flagBadCentroid] INT NULL ,
	[r_flagBadShape] INT NULL ,
	[i_psfFlux] FLOAT NULL ,
	[i_psfFluxSigma] FLOAT NULL ,
	[i_apFlux] FLOAT NULL ,
	[i_apFluxSigma] FLOAT NULL ,
	[i_modelFlux] FLOAT NULL ,
	[i_modelFluxSigma] FLOAT NULL ,
	[i_instFlux] FLOAT NULL ,
	[i_instFluxSigma] FLOAT NULL ,
	[i_apCorrection] FLOAT NULL ,
	[i_apCorrectionSigma] FLOAT NULL ,
	[i_shapeIx] FLOAT NULL ,
	[i_shapeIy] FLOAT NULL ,
	[i_shapeIxVar] FLOAT NULL ,
	[i_shapeIyVar] FLOAT NULL ,
	[i_shapeIxIyCov] FLOAT NULL ,
	[i_shapeIxx] FLOAT NULL ,
	[i_shapeIyy] FLOAT NULL ,
	[i_shapeIxy] FLOAT NULL ,
	[i_shapeIxxVar] FLOAT NULL ,
	[i_shapeIyyVar] FLOAT NULL ,
	[i_shapeIxyVar] FLOAT NULL ,
	[i_shapeIxxIyyCov] FLOAT NULL ,
	[i_shapeIxxIxyCov] FLOAT NULL ,
	[i_shapeIyyIxyCov] FLOAT NULL ,
	[i_extendedness] FLOAT NULL ,
	[i_flagNegative] INT NULL ,
	[i_flagBadMeasCentroid] INT NULL ,
	[i_flagPixEdge] INT NULL ,
	[i_flagPixInterpAny] INT NULL ,
	[i_flagPixInterpCen] INT NULL ,
	[i_flagPixSaturAny] INT NULL ,
	[i_flagPixSaturCen] INT NULL ,
	[i_flagBadPsfFlux] INT NULL ,
	[i_flagBadApFlux] INT NULL ,
	[i_flagBadModelFlux] INT NULL ,
	[i_flagBadInstFlux] INT NULL ,
	[i_flagBadCentroid] INT NULL ,
	[i_flagBadShape] INT NULL ,
	[z_psfFlux] FLOAT NULL ,
	[z_psfFluxSigma] FLOAT NULL ,
	[z_apFlux] FLOAT NULL ,
	[z_apFluxSigma] FLOAT NULL ,
	[z_modelFlux] FLOAT NULL ,
	[z_modelFluxSigma] FLOAT NULL ,
	[z_instFlux] FLOAT NULL ,
	[z_instFluxSigma] FLOAT NULL ,
	[z_apCorrection] FLOAT NULL ,
	[z_apCorrectionSigma] FLOAT NULL ,
	[z_shapeIx] FLOAT NULL ,
	[z_shapeIy] FLOAT NULL ,
	[z_shapeIxVar] FLOAT NULL ,
	[z_shapeIyVar] FLOAT NULL ,
	[z_shapeIxIyCov] FLOAT NULL ,
	[z_shapeIxx] FLOAT NULL ,
	[z_shapeIyy] FLOAT NULL ,
	[z_shapeIxy] FLOAT NULL ,
	[z_shapeIxxVar] FLOAT NULL ,
	[z_shapeIyyVar] FLOAT NULL ,
	[z_shapeIxyVar] FLOAT NULL ,
	[z_shapeIxxIyyCov] FLOAT NULL ,
	[z_shapeIxxIxyCov] FLOAT NULL ,
	[z_shapeIyyIxyCov] FLOAT NULL ,
	[z_extendedness] FLOAT NULL ,
	[z_flagNegative] INT NULL ,
	[z_flagBadMeasCentroid] INT NULL ,
	[z_flagPixEdge] INT NULL ,
	[z_flagPixInterpAny] INT NULL ,
	[z_flagPixInterpCen] INT NULL ,
	[z_flagPixSaturAny] INT NULL ,
	[z_flagPixSaturCen] INT NULL ,
	[z_flagBadPsfFlux] INT NULL ,
	[z_flagBadApFlux] INT NULL ,
	[z_flagBadModelFlux] INT NULL ,
	[z_flagBadInstFlux] INT NULL ,
	[z_flagBadCentroid] INT NULL ,
	[z_flagBadShape] INT NULL ,
	[y_psfFlux] FLOAT NULL ,
	[y_psfFluxSigma] FLOAT NULL ,
	[y_apFlux] FLOAT NULL ,
	[y_apFluxSigma] FLOAT NULL ,
	[y_modelFlux] FLOAT NULL ,
	[y_modelFluxSigma] FLOAT NULL ,
	[y_instFlux] FLOAT NULL ,
	[y_instFluxSigma] FLOAT NULL ,
	[y_apCorrection] FLOAT NULL ,
	[y_apCorrectionSigma] FLOAT NULL ,
	[y_shapeIx] FLOAT NULL ,
	[y_shapeIy] FLOAT NULL ,
	[y_shapeIxVar] FLOAT NULL ,
	[y_shapeIyVar] FLOAT NULL ,
	[y_shapeIxIyCov] FLOAT NULL ,
	[y_shapeIxx] FLOAT NULL ,
	[y_shapeIyy] FLOAT NULL ,
	[y_shapeIxy] FLOAT NULL ,
	[y_shapeIxxVar] FLOAT NULL ,
	[y_shapeIyyVar] FLOAT NULL ,
	[y_shapeIxyVar] FLOAT NULL ,
	[y_shapeIxxIyyCov] FLOAT NULL ,
	[y_shapeIxxIxyCov] FLOAT NULL ,
	[y_shapeIyyIxyCov] FLOAT NULL ,
	[y_extendedness] FLOAT NULL ,
	[y_flagNegative] INT NULL ,
	[y_flagBadMeasCentroid] INT NULL ,
	[y_flagPixEdge] INT NULL ,
	[y_flagPixInterpAny] INT NULL ,
	[y_flagPixInterpCen] INT NULL ,
	[y_flagPixSaturAny] INT NULL ,
	[y_flagPixSaturCen] INT NULL ,
	[y_flagBadPsfFlux] INT NULL ,
	[y_flagBadApFlux] INT NULL ,
	[y_flagBadModelFlux] INT NULL ,
	[y_flagBadInstFlux] INT NULL ,
	[y_flagBadCentroid] INT NULL ,
	[y_flagBadShape] INT NULL,
	[htmid] bigint null
	--PRIMARY KEY ([deepSourceId])
)
    WITH
    (
        DATA_SOURCE = SqlDataPool,
        DISTRIBUTION = REPLICATED
    );
GO
--CREATE INDEX [subChunkId] ON Object ([subChunkId]);

--select count(*) from [Object]
--78754603 lines of csv

--select top 800 * from Object
--select top 10 * from [Object] order by ra desc
--select count(chunkID) from [Object]
--select avg(ra) from [Object]
--select count(distinct deepSourceId) from [Object]
--select distinct chunkID from [Object]
--select * from object where deepSourceId = 2567518564647597

--truncate table Object

--create STATISTICS foo on OBJECT (deepSourceId, chunkId) with fullscan