apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    MSSQL_CLUSTER: filedb
    app: controller
    plane: control
    role: controller
  name: controller-svc-external
  selfLink: /api/v1/namespaces/filedb/services/controller-svc-external
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 443
    protocol: TCP
    targetPort: controller-port
  selector:
    app: controller
    plane: control
    role: controller
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
