apiVersion: v1
kind: Service
metadata:
  name: mssql-masternode
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 1433
    protocol: TCP
  selector:
    app: mssql-compute-pool-master
    component: mssql-compute-pool-master
    statefulset.kubernetes.io/pod-name: mssql-compute-pool-master-0
  type: NodePort
