apiVersion: v1
kind: Service
metadata:
  name: mssql-node2
  namespace: default
spec:
  ports:
  - nodePort: 32003
    port: 1433
    protocol: TCP
  selector:
    app: mssql-compute-pool-node
    component: mssql-compute-pool-node
    statefulset.kubernetes.io/pod-name: mssql-compute-pool-node-2
  type: NodePort
