apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb10-1da61278-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-174f1e2a
    selfLink: /api/v1/persistentvolumes/local-pv-174f1e2a
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-3
      namespace: filedb
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb10
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status: {}
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb01-4ae19aeb-0ecd-11e9-855b-0cc47ad46d50
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-4903b508
    selfLink: /api/v1/persistentvolumes/local-pv-4903b508
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-2
      namespace: filedb
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb01
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status: {}
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb11-45107117-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-a41e3121
    selfLink: /api/v1/persistentvolumes/local-pv-a41e3121
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-1
      namespace: filedb
    local:
      path: /srv/data03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status: {}
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb12-1e8eb8db-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-e7eba29e
    selfLink: /api/v1/persistentvolumes/local-pv-e7eba29e
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-0
      namespace: filedb
    local:
      path: /srv/data03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
