apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb10-1da61278-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:19:58Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-174f1e2a
    resourceVersion: "69243368"
    selfLink: /api/v1/persistentvolumes/local-pv-174f1e2a
    uid: 61941bb8-1831-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-3
      namespace: filedb
      resourceVersion: "68905299"
      uid: 15cca9d6-8661-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb10
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/provisioned-by":"local-volume-provisioner-filedb01-4ae19aeb-0ecd-11e9-855b-0cc47ad46d50"},"creationTimestamp":"2019-03-05T21:03:46Z","finalizers":["kubernetes.io/pv-protection"],"name":"local-pv-24566b13","resourceVersion":"68811847","selfLink":"/api/v1/persistentvolumes/local-pv-24566b13","uid":"2ace0518-3f8a-11e9-a147-0cc47ad46d50"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"55887Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"data-data-0-2","namespace":"filedb"},"local":{"path":"/srv/data02"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["filedb01"]}]}]}},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"local-storage","volumeMode":"Filesystem"},"status":{"phase":"Available"}}
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb01-4ae19aeb-0ecd-11e9-855b-0cc47ad46d50
    creationTimestamp: "2019-03-05T21:03:46Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-24566b13
    resourceVersion: "69243328"
    selfLink: /api/v1/persistentvolumes/local-pv-24566b13
    uid: 2ace0518-3f8a-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-data-0-2
      namespace: filedb
      resourceVersion: "68878186"
      uid: ad811ae8-8648-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data02
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb01
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb01-4ae19aeb-0ecd-11e9-855b-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:20:01Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-4903b508
    resourceVersion: "69243363"
    selfLink: /api/v1/persistentvolumes/local-pv-4903b508
    uid: 63aadc4e-1831-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-2
      namespace: filedb
      resourceVersion: "68905295"
      uid: 15cbcde6-8661-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb01
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/bound-by-controller":"yes","pv.kubernetes.io/provisioned-by":"local-volume-provisioner-filedb10-1da61278-3385-11e8-9edf-0cc47ad46d50"},"creationTimestamp":"2019-01-14T19:29:08Z","finalizers":["kubernetes.io/pv-protection"],"name":"local-pv-740f1d60","resourceVersion":"68811851","selfLink":"/api/v1/persistentvolumes/local-pv-740f1d60","uid":"a970abd3-1832-11e9-a147-0cc47ad46d50"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"55887Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"data-data-0-0","namespace":"filedb"},"local":{"path":"/srv/data03"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["filedb10"]}]}]}},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"local-storage","volumeMode":"Filesystem"},"status":{"phase":"Available"}}
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb10-1da61278-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:29:08Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-740f1d60
    resourceVersion: "69243323"
    selfLink: /api/v1/persistentvolumes/local-pv-740f1d60
    uid: a970abd3-1832-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-data-0-0
      namespace: filedb
      resourceVersion: "68878168"
      uid: ad7f6959-8648-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb10
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/bound-by-controller":"yes","pv.kubernetes.io/provisioned-by":"local-volume-provisioner-filedb12-1e8eb8db-3385-11e8-9edf-0cc47ad46d50"},"creationTimestamp":"2019-01-14T19:29:07Z","finalizers":["kubernetes.io/pv-protection"],"name":"local-pv-8961a58c","resourceVersion":"68811853","selfLink":"/api/v1/persistentvolumes/local-pv-8961a58c","uid":"a934145b-1832-11e9-a147-0cc47ad46d50"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"55887Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"data-data-0-3","namespace":"filedb"},"local":{"path":"/srv/data01"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["filedb12"]}]}]}},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"local-storage","volumeMode":"Filesystem"},"status":{"phase":"Available"}}
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb12-1e8eb8db-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:29:07Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-8961a58c
    resourceVersion: "69243334"
    selfLink: /api/v1/persistentvolumes/local-pv-8961a58c
    uid: a934145b-1832-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-data-0-3
      namespace: filedb
      resourceVersion: "68878197"
      uid: ad82061a-8648-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/bound-by-controller":"yes","pv.kubernetes.io/provisioned-by":"local-volume-provisioner-filedb11-45107117-3385-11e8-9edf-0cc47ad46d50"},"creationTimestamp":"2019-01-14T19:29:09Z","finalizers":["kubernetes.io/pv-protection"],"name":"local-pv-9fe86233","resourceVersion":"68811855","selfLink":"/api/v1/persistentvolumes/local-pv-9fe86233","uid":"a9fd68ab-1832-11e9-a147-0cc47ad46d50"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"55887Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"data-data-0-1","namespace":"filedb"},"local":{"path":"/srv/data01"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["filedb11"]}]}]}},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"local-storage","volumeMode":"Filesystem"},"status":{"phase":"Available"}}
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb11-45107117-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:29:09Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-9fe86233
    resourceVersion: "69243326"
    selfLink: /api/v1/persistentvolumes/local-pv-9fe86233
    uid: a9fd68ab-1832-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-data-0-1
      namespace: filedb
      resourceVersion: "68878174"
      uid: ad805a63-8648-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb11-45107117-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:19:59Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-a41e3121
    resourceVersion: "69243359"
    selfLink: /api/v1/persistentvolumes/local-pv-a41e3121
    uid: 62208630-1831-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-1
      namespace: filedb
      resourceVersion: "68905283"
      uid: 15cac40c-8661-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb11
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb14-23f15f63-3745-11e8-bf20-0cc47ad46d50
    creationTimestamp: "2019-03-05T20:06:35Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-cf98ab10
    resourceVersion: "69243440"
    selfLink: /api/v1/persistentvolumes/local-pv-cf98ab10
    uid: 2dc11e2d-3f82-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1117Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-nmnode-0-0
      namespace: filedb
      resourceVersion: "68904948"
      uid: d29bea8b-8660-11e9-a147-0cc47ad46d50
    local:
      path: /nvme/nvme02
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb14
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage-nvme
    volumeMode: Filesystem
  status:
    phase: Released
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: local-volume-provisioner-filedb12-1e8eb8db-3385-11e8-9edf-0cc47ad46d50
    creationTimestamp: "2019-01-14T19:19:57Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: local-pv-e7eba29e
    resourceVersion: "69243355"
    selfLink: /api/v1/persistentvolumes/local-pv-e7eba29e
    uid: 6157c60a-1831-11e9-a147-0cc47ad46d50
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 55887Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-storage-0-0
      namespace: filedb
      resourceVersion: "68905274"
      uid: 15c8ab63-8661-11e9-a147-0cc47ad46d50
    local:
      path: /srv/data03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - filedb12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Released
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
