apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    MSSQL_CLUSTER: filedb
  name: mssql-data-pool-default
  namespace: filedb
  selfLink: /apis/apps/v1/namespaces/filedb/statefulsets/mssql-data-pool-default
spec:
  podManagementPolicy: Parallel
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      MSSQL_CLUSTER: filedb
      app: mssql-data-pool-default
  serviceName: service-data-pool-default
  template:
    metadata:
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedb
        app: mssql-data-pool-default
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mssql-data-pool-default
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: mssql-data-pool
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-server
        - name: ACCEPT_EULA
          value: "Y"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-server-data:ctp2.4
        imagePullPolicy: Always
        name: mssql-server
        ports:
        - containerPort: 1433
          name: port-1433
          protocol: TCP
        - containerPort: 8301
          name: agent-port-8301
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /var/run/container.ready
          failureThreshold: 210
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: pvc-data2
          subPath: Aris/mssql-data-pool-default/var.ctp2.4/opt
        - mountPath: /pvcadmin
          name: pvc-data2
          subPath: Aris
        - mountPath: /sciserver
          name: autofs-sciserver
        - mountPath: /srv
          name: srv
        - mountPath: /nvme
          name: nvme
      - env:
        - name: MONITORING_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: INFLUX_DB_SERVER
          value: service-monitor-influxdb
        - name: INFLUX_DB_PORT
          value: "25826"
        - name: SQL_HOSTNAME
          value: 127.0.0.1
        - name: SQL_POLL_INTERVAL
          value: "5"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-collectd:ctp2.4
        imagePullPolicy: Always
        name: mssql-monitor-collectd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: pvc-data2
          subPath: Aris/mssql-data-pool-default/var.ctp2.4/opt
        - mountPath: /sciserver
          name: autofs-sciserver
        - mountPath: /srv
          name: srv
        - mountPath: /nvme
          name: nvme
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: service-monitor-elasticsearch
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENTBIT_CONFIG
          value: fluentbit-data-pool-default.conf
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-fluentbit:ctp2.4
        imagePullPolicy: Always
        name: mssql-monitor-fluentbit
        ports:
        - containerPort: 2020
          name: fluentb-2020
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt
          name: pvc-data2
          subPath: Aris/mssql-data-pool-default/var.ctp2.4/opt
        - mountPath: /sciserver
          name: autofs-sciserver
        - mountPath: /srv
          name: srv
        - mountPath: /nvme
          name: nvme
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mssql-private-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: mssql-data-pool-default-secret
      - name: autofs-sciserver
        hostPath:
          path: /sciserver
      - name: srv
        hostPath:
          path: /srv
      - name: nvme
        hostPath:
          path: /nvme
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: pvc-data2
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5000Gi
      storageClassName: local-storage
status:
  replicas: 0
