apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    MSSQL_CLUSTER: filedbtest
  name: mssql-monitor-elasticsearch
  selfLink: /apis/apps/v1/namespaces/filedbtest/statefulsets/mssql-monitor-elasticsearch
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mssql-monitor-elasticsearch
      task: mssql-monitor
  serviceName: service-monitor-elasticsearch
  template:
    metadata:
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedbtest
        app: mssql-monitor-elasticsearch
        task: mssql-monitor
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-elasticsearch:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: es-transport
          timeoutSeconds: 90
        name: mssql-monitor-elasticsearch
        ports:
        - containerPort: 9200
          name: es-http
          protocol: TCP
        - containerPort: 9300
          name: es-transport
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/elasticsearch
          name: elasticsearch-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mssql-private-registry
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-elasticsearch:latest
        imagePullPolicy: Always
        name: init-sysctl
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: elasticsearch-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0
