apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    MSSQL_CLUSTER: filedbtest
  name: mssql-security
  selfLink: /apis/apps/v1/namespaces/filedbtest/statefulsets/mssql-security
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mssql-security
  serviceName: service-security
  template:
    metadata:
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedbtest
        app: mssql-security
    spec:
      containers:
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: mssql-security
        - name: MSSQL_CONTAINER_TYPE
          value: knox
        image: private-repo.microsoft.com/mssql-private-preview/mssql-security-knox:latest
        imagePullPolicy: Always
        name: knox
        ports:
        - containerPort: 8443
          name: knox-8443
          protocol: TCP
        - containerPort: 33389
          name: ldap-33389
          protocol: TCP
        - containerPort: 8302
          name: agent-port-8302
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: security-storage
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: security
        - name: MSSQL_CONTAINER_TYPE
          value: ranger
        image: private-repo.microsoft.com/mssql-private-preview/mssql-security-ranger:latest
        imagePullPolicy: Always
        name: ranger
        ports:
        - containerPort: 6080
          name: ranger-6080
          protocol: TCP
        - containerPort: 8983
          name: rangersolr-8983
          protocol: TCP
        - containerPort: 8303
          name: agent-port-8303
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: security-storage
        - mountPath: /var/log/ranger
          name: ranger-storage
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: security
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-server
        - name: ACCEPT_EULA
          value: "Y"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-server-security:latest
        imagePullPolicy: Always
        name: mssql-server-security
        ports:
        - containerPort: 1433
          name: port-1433
          protocol: TCP
        - containerPort: 8301
          name: agent-port-8301
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: security-storage
        - mountPath: /knox/logs
          name: knox-storage
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: service-monitor-elasticsearch
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENTBIT_CONFIG
          value: fluentbit-security.conf
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-fluentbit:latest
        imagePullPolicy: Always
        name: mssql-monitor-fluentbit
        ports:
        - containerPort: 2020
          name: fluentb-2020
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt
          name: security-storage
        - mountPath: /var/log/ranger
          name: ranger-storage
          readOnly: true
        - mountPath: /knox/logs
          name: knox-storage
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mssql-private-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: mssql-security-secret
      - emptyDir: {}
        name: ranger-storage
      - emptyDir: {}
        name: knox-storage
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: security-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0
