apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-01-11T18:47:27Z"
  generation: 1
  labels:
    MSSQL_CLUSTER: filedb
  name: mssql-master-pool
  namespace: filedb
  resourceVersion: "39460857"
  selfLink: /apis/apps/v1/namespaces/filedb/statefulsets/mssql-master-pool
  uid: 57d810f9-15d1-11e9-a147-0cc47ad46d50
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mssql-master-pool
  serviceName: service-master-pool
  template:
    metadata:
      creationTimestamp: null
      labels:
        MSSQL_CLUSTER: filedb
        app: mssql-master-pool
    spec:
      containers:
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: mssql-master-pool
        - name: MSSQL_CONTAINER_TYPE
          value: hadoop
        - name: AGENT_CONFIG_FILE
          value: /opt/agent/config/master.json
        - name: HADOOP_HEAPSIZE
          value: "2048"
        - name: YARN_HEAPSIZE
          value: "2048"
        - name: YARN_SCHEDULER_MAX_MEMORY
          value: "18432"
        - name: YARN_SCHEDULER_MAX_VCORES
          value: "6"
        - name: YARN_NODEMANAGER_RESOURCE_MEMORY
          value: "18432"
        - name: YARN_NODEMANAGER_RESOURCE_VCORES
          value: "6"
        - name: YARN_SCHEDULER_CAPACITY_MAX_AM_PERCENT
          value: "0.3"
        - name: SPARK_DRIVER_MEMORY
          value: 2g
        - name: SPARK_DRIVER_CORES
          value: "1"
        - name: SPARK_EXECUTOR_INSTANCES
          value: "3"
        - name: SPARK_EXECUTOR_MEMORY
          value: 1536m
        - name: SPARK_EXECUTOR_CORES
          value: "1"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-hadoop:latest
        imagePullPolicy: Always
        name: hadoop
        ports:
        - containerPort: 8088
          name: port-8088
          protocol: TCP
        - containerPort: 50070
          name: port-50070
          protocol: TCP
        - containerPort: 50075
          name: port-50075
          protocol: TCP
        - containerPort: 50020
          name: port-50020
          protocol: TCP
        - containerPort: 9000
          name: port-9000
          protocol: TCP
        - containerPort: 50010
          name: port-50010
          protocol: TCP
        - containerPort: 8030
          name: port-8030
          protocol: TCP
        - containerPort: 8031
          name: port-8031
          protocol: TCP
        - containerPort: 8032
          name: port-8032
          protocol: TCP
        - containerPort: 8033
          name: port-8033
          protocol: TCP
        - containerPort: 8040
          name: port-8040
          protocol: TCP
        - containerPort: 8042
          name: port-8042
          protocol: TCP
        - containerPort: 14000
          name: port-14000
          protocol: TCP
        - containerPort: 8998
          name: port-8998
          protocol: TCP
        - containerPort: 8302
          name: agent-port-8302
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/opt
          name: master-pool-storage
        - mountPath: /root/hdfs/namenode
          name: hdfs
        - mountPath: /opt/mssql/mlservices
          name: master-pool-mlservices-storage
        - mountPath: /opt/mssql/mssql-java
          name: master-pool-java-storage
        - mountPath: /usr/local/hadoop/logs
          name: hadoop-logs
      - env:
        - name: MSSQL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MSSQL_POD_TYPE
          value: mssql-master-pool
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-server
        - name: ACCEPT_EULA
          value: "Y"
        - name: ACCEPT_EULA_ML
          value: "Y"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-server-data:latest
        imagePullPolicy: Always
        name: mssql-server
        ports:
        - containerPort: 1433
          name: port-1433
          protocol: TCP
        - containerPort: 8301
          name: agent-port-8301
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /var/run/container.ready
          failureThreshold: 210
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
        - mountPath: /root/secrets/node-admin-login
          name: node-admin-login-secrets
          readOnly: true
        - mountPath: /var/opt
          name: master-pool-storage
        - mountPath: /opt/mssql/mlservices
          name: master-pool-mlservices-storage
        - mountPath: /opt/mssql/java
          name: master-pool-java-storage
      - env:
        - name: MSSQL_POD_TYPE
          value: mssql-master-pool
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-mlservices-rserver
        - name: ACCEPT_EULA
          value: "Y"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-mlservices-rserver:latest
        imagePullPolicy: Always
        name: mssql-mlservices-rserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/mlservices
          name: master-pool-mlservices-storage
      - env:
        - name: MSSQL_POD_TYPE
          value: mssql-master-pool
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-mlservices-pythonserver
        - name: ACCEPT_EULA
          value: "Y"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-mlservices-pythonserver:latest
        imagePullPolicy: Always
        name: mssql-mlservices-pythonserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/mlservices
          name: master-pool-mlservices-storage
      - env:
        - name: MSSQL_POD_TYPE
          value: mssql-master-pool
        - name: MSSQL_CONTAINER_TYPE
          value: mssql-java
        image: private-repo.microsoft.com/mssql-private-preview/mssql-java:latest
        imagePullPolicy: Always
        name: mssql-java
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/shared/java
          name: master-pool-java-storage
      - env:
        - name: MONITORING_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: INFLUX_DB_SERVER
          value: service-monitor-influxdb
        - name: INFLUX_DB_PORT
          value: "25826"
        - name: SQL_HOSTNAME
          value: 127.0.0.1
        - name: SQL_POLL_INTERVAL
          value: "5"
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-collectd:latest
        imagePullPolicy: Always
        name: mssql-monitor-collectd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/secrets
          name: secrets
          readOnly: true
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: service-monitor-elasticsearch
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENTBIT_CONFIG
          value: fluentbit-master-pool.conf
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: private-repo.microsoft.com/mssql-private-preview/mssql-monitor-fluentbit:latest
        imagePullPolicy: Always
        name: mssql-monitor-fluentbit
        ports:
        - containerPort: 2020
          name: fluentb-2020
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt
          name: master-pool-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mssql-private-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: mssql-master-pool-secret
      - name: node-admin-login-secrets
        secret:
          defaultMode: 420
          secretName: node-admin-login-secret
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: master-pool-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: hadoop-logs
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: master-pool-mlservices-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: hdfs
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: master-pool-java-storage
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 6Gi
      storageClassName: managed-premium
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mssql-master-pool-55dbcd6779
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: mssql-master-pool-55dbcd6779
  updatedReplicas: 1
