USE [master]
GO

/****** Object:  Database [lsst_stage]    Script Date: 2/16/2018 1:58:00 PM ******/
CREATE DATABASE [lsst_stage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lsst_stage', FILENAME = N'c:\pool\sql_db\lsst_stage.mdf' , SIZE = 12800000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 512000KB ), 
 FILEGROUP [ST_01] 
( NAME = N'stage01', FILENAME = N'c:\ssd\sql_db\stage01.ndf' , SIZE = 104857600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'lsst_stage_log', FILENAME = N'c:\pool\sql_log\lsst_stage_log.ldf' , SIZE = 15081472KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [lsst_stage] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lsst_stage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lsst_stage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lsst_stage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lsst_stage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lsst_stage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lsst_stage] SET ARITHABORT OFF 
GO

ALTER DATABASE [lsst_stage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lsst_stage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lsst_stage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lsst_stage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lsst_stage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lsst_stage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lsst_stage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lsst_stage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lsst_stage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lsst_stage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lsst_stage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lsst_stage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lsst_stage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lsst_stage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lsst_stage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lsst_stage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lsst_stage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lsst_stage] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [lsst_stage] SET  MULTI_USER 
GO

ALTER DATABASE [lsst_stage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lsst_stage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lsst_stage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lsst_stage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [lsst_stage] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lsst_stage] SET QUERY_STORE = ON
GO

ALTER DATABASE [lsst_stage] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

USE [lsst_stage]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [lsst_stage] SET  READ_WRITE 
GO


