USE [master]
GO

/*
alter database LSST_03
set single_user with rollback immediate

drop database LSST_03
*/

/****** Object:  Database [LSST_03]    Script Date: 2/16/2018 1:26:58 PM ******/
CREATE DATABASE [LSST_03]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LSST_03', FILENAME = N'C:\pool\sql_db\LSST_03\LSST_03.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [FS_03] 
( NAME = N'forcedsource_03', FILENAME = N'C:\pool\sql_db\LSST_03\forcedsource_03.ndf' , SIZE = 30GB , MAXSIZE = UNLIMITED, FILEGROWTH = 204800KB ), 
 FILEGROUP [OBJ_03] 
( NAME = N'object_03', FILENAME = N'C:\pool\sql_db\LSST_03\object_03.ndf' , SIZE = 20GB , MAXSIZE = UNLIMITED, FILEGROWTH = 204800KB ), 
 FILEGROUP [SRC_03] 
( NAME = N'source_03', FILENAME = N'C:\pool\sql_db\LSST_03\source_03.ndf' , SIZE = 80GB , MAXSIZE = UNLIMITED, FILEGROWTH = 204800KB )
 LOG ON 
( NAME = N'LSST_03_log', FILENAME = N'C:\pool\sql_log\LSST_03_log.ldf' , SIZE = 82714624KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LSST_03].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LSST_03] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LSST_03] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LSST_03] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LSST_03] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LSST_03] SET ARITHABORT OFF 
GO

ALTER DATABASE [LSST_03] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LSST_03] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LSST_03] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LSST_03] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LSST_03] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LSST_03] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LSST_03] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LSST_03] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LSST_03] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LSST_03] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LSST_03] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LSST_03] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LSST_03] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LSST_03] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LSST_03] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LSST_03] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LSST_03] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LSST_03] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LSST_03] SET  MULTI_USER 
GO

ALTER DATABASE [LSST_03] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LSST_03] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LSST_03] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LSST_03] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LSST_03] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LSST_03] SET QUERY_STORE = ON
GO

USE [LSST_03]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LSST_03] SET  READ_WRITE 
GO


