insert LSST_01.dbo.Object_01
select
deepSourceId, 
ra, 
decl, 
case raVar when 'null' then null else raVar end as raVar, 
case declVar when 'null' then null else declVar end as declVar, 
case radeclCov when 'null' then null else radeclCov end as radeclCov, 
LSST20.htmid.FromEq(ra, decl),
chunkId, 
subChunkId, 
case u_psfFlux when 'null' then null else u_psfFlux end as u_psfFlux, 
case u_psfFluxSigma when 'null' then null else u_psfFluxSigma end as u_psfFluxSigma, 
case u_apFlux when 'null' then null else u_apFlux end as u_apFlux, 
case u_apFluxSigma when 'null' then null else u_apFluxSigma end as u_apFluxSigma, 
case u_modelFlux when 'null' then null else u_modelFlux end as u_modelFlux, 
case u_modelFluxSigma when 'null' then null else u_modelFluxSigma end as u_modelFluxSigma, 
case u_instFlux when 'null' then null else u_instFlux end as u_instFlux, 
case u_instFluxSigma when 'null' then null else u_instFluxSigma end as u_instFluxSigma, 
case u_apCorrection when 'null' then null else u_apCorrection end as u_apCorrection, 
case u_apCorrectionSigma when 'null' then null else u_apCorrectionSigma end as u_apCorrectionSigma, 
case u_shapeIx when 'null' then null else u_shapeIx end as u_shapeIx, 
case u_shapeIy when 'null' then null else u_shapeIy end as u_shapeIy, 
case u_shapeIxVar when 'null' then null else u_shapeIxVar end as u_shapeIxVar, 
case u_shapeIyVar when 'null' then null else u_shapeIyVar end as u_shapeIyVar, 
case u_shapeIxIyCov when 'null' then null else u_shapeIxIyCov end as u_shapeIxIyCov, 
case u_shapeIxx when 'null' then null else u_shapeIxx end as u_shapeIxx, 
case u_shapeIyy when 'null' then null else u_shapeIyy end as u_shapeIyy, 
case u_shapeIxy when 'null' then null else u_shapeIxy end as u_shapeIxy, 
case u_shapeIxxVar when 'null' then null else u_shapeIxxVar end as u_shapeIxxVar, 
case u_shapeIyyVar when 'null' then null else u_shapeIyyVar end as u_shapeIyyVar, 
case u_shapeIxyVar when 'null' then null else u_shapeIxyVar end as u_shapeIxyVar, 
case u_shapeIxxIyyCov when 'null' then null else u_shapeIxxIyyCov end as u_shapeIxxIyyCov, 
case u_shapeIxxIxyCov when 'null' then null else u_shapeIxxIxyCov end as u_shapeIxxIxyCov, 
case u_shapeIyyIxyCov when 'null' then null else u_shapeIyyIxyCov end as u_shapeIyyIxyCov, 
case u_extendedness when 'null' then null else u_extendedness end as u_extendedness, 
case u_flagNegative when '0' then 0 when '1' then 1 else null end as u_flagNegative, 
case u_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as u_flagBadMeasCentroid, 
case u_flagPixEdge when '0' then 0 when '1' then 1 else null end as u_flagPixEdge, 
case u_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as u_flagPixInterpAny, 
case u_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as u_flagPixInterpCen, 
case u_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as u_flagPixSaturAny, 
case u_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as u_flagPixSaturCen, 
case u_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as u_flagBadPsfFlux, 
case u_flagBadApFlux when '0' then 0 when '1' then 1 else null end as u_flagBadApFlux, 
case u_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as u_flagBadModelFlux, 
case u_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as u_flagBadInstFlux, 
case u_flagBadCentroid when '0' then 0 when '1' then 1 else null end as u_flagBadCentroid, 
case u_flagBadShape when '0' then 0 when '1' then 1 else null end as u_flagBadShape, 
case g_psfFlux when 'null' then null else g_psfFlux end as g_psfFlux, 
case g_psfFluxSigma when 'null' then null else g_psfFluxSigma end as g_psfFluxSigma, 
case g_apFlux when 'null' then null else g_apFlux end as g_apFlux, 
case g_apFluxSigma when 'null' then null else g_apFluxSigma end as g_apFluxSigma, 
case g_modelFlux when 'null' then null else g_modelFlux end as g_modelFlux, 
case g_modelFluxSigma when 'null' then null else g_modelFluxSigma end as g_modelFluxSigma, 
case g_instFlux when 'null' then null else g_instFlux end as g_instFlux, 
case g_instFluxSigma when 'null' then null else g_instFluxSigma end as g_instFluxSigma, 
case g_apCorrection when 'null' then null else g_apCorrection end as g_apCorrection, 
case g_apCorrectionSigma when 'null' then null else g_apCorrectionSigma end as g_apCorrectionSigma, 
case g_shapeIx when 'null' then null else g_shapeIx end as g_shapeIx, 
case g_shapeIy when 'null' then null else g_shapeIy end as g_shapeIy, 
case g_shapeIxVar when 'null' then null else g_shapeIxVar end as g_shapeIxVar, 
case g_shapeIyVar when 'null' then null else g_shapeIyVar end as g_shapeIyVar, 
case g_shapeIxIyCov when 'null' then null else g_shapeIxIyCov end as g_shapeIxIyCov, 
case g_shapeIxx when 'null' then null else g_shapeIxx end as g_shapeIxx, 
case g_shapeIyy when 'null' then null else g_shapeIyy end as g_shapeIyy, 
case g_shapeIxy when 'null' then null else g_shapeIxy end as g_shapeIxy, 
case g_shapeIxxVar when 'null' then null else g_shapeIxxVar end as g_shapeIxxVar, 
case g_shapeIyyVar when 'null' then null else g_shapeIyyVar end as g_shapeIyyVar, 
case g_shapeIxyVar when 'null' then null else g_shapeIxyVar end as g_shapeIxyVar, 
case g_shapeIxxIyyCov when 'null' then null else g_shapeIxxIyyCov end as g_shapeIxxIyyCov, 
case g_shapeIxxIxyCov when 'null' then null else g_shapeIxxIxyCov end as g_shapeIxxIxyCov, 
case g_shapeIyyIxyCov when 'null' then null else g_shapeIyyIxyCov end as g_shapeIyyIxyCov, 
case g_extendedness when 'null' then null else g_extendedness end as g_extendedness, 
case g_flagNegative when '0' then 0 when '1' then 1 else null end as g_flagNegative, 
case g_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as g_flagBadMeasCentroid, 
case g_flagPixEdge when '0' then 0 when '1' then 1 else null end as g_flagPixEdge, 
case g_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as g_flagPixInterpAny, 
case g_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as g_flagPixInterpCen, 
case g_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as g_flagPixSaturAny, 
case g_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as g_flagPixSaturCen, 
case g_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as g_flagBadPsfFlux, 
case g_flagBadApFlux when '0' then 0 when '1' then 1 else null end as g_flagBadApFlux, 
case g_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as g_flagBadModelFlux, 
case g_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as g_flagBadInstFlux, 
case g_flagBadCentroid when '0' then 0 when '1' then 1 else null end as g_flagBadCentroid, 
case g_flagBadShape when '0' then 0 when '1' then 1 else null end as g_flagBadShape, 
case r_psfFlux when 'null' then null else r_psfFlux end as r_psfFlux, 
case r_psfFluxSigma when 'null' then null else r_psfFluxSigma end as r_psfFluxSigma, 
case r_apFlux when 'null' then null else r_apFlux end as r_apFlux, 
case r_apFluxSigma when 'null' then null else r_apFluxSigma end as r_apFluxSigma, 
case r_modelFlux when 'null' then null else r_modelFlux end as r_modelFlux, 
case r_modelFluxSigma when 'null' then null else r_modelFluxSigma end as r_modelFluxSigma, 
case r_instFlux when 'null' then null else r_instFlux end as r_instFlux, 
case r_instFluxSigma when 'null' then null else r_instFluxSigma end as r_instFluxSigma, 
case r_apCorrection when 'null' then null else r_apCorrection end as r_apCorrection, 
case r_apCorrectionSigma when 'null' then null else r_apCorrectionSigma end as r_apCorrectionSigma, 
case r_shapeIx when 'null' then null else r_shapeIx end as r_shapeIx, 
case r_shapeIy when 'null' then null else r_shapeIy end as r_shapeIy, 
case r_shapeIxVar when 'null' then null else r_shapeIxVar end as r_shapeIxVar, 
case r_shapeIyVar when 'null' then null else r_shapeIyVar end as r_shapeIyVar, 
case r_shapeIxIyCov when 'null' then null else r_shapeIxIyCov end as r_shapeIxIyCov, 
case r_shapeIxx when 'null' then null else r_shapeIxx end as r_shapeIxx, 
case r_shapeIyy when 'null' then null else r_shapeIyy end as r_shapeIyy, 
case r_shapeIxy when 'null' then null else r_shapeIxy end as r_shapeIxy, 
case r_shapeIxxVar when 'null' then null else r_shapeIxxVar end as r_shapeIxxVar, 
case r_shapeIyyVar when 'null' then null else r_shapeIyyVar end as r_shapeIyyVar, 
case r_shapeIxyVar when 'null' then null else r_shapeIxyVar end as r_shapeIxyVar, 
case r_shapeIxxIyyCov when 'null' then null else r_shapeIxxIyyCov end as r_shapeIxxIyyCov, 
case r_shapeIxxIxyCov when 'null' then null else r_shapeIxxIxyCov end as r_shapeIxxIxyCov, 
case r_shapeIyyIxyCov when 'null' then null else r_shapeIyyIxyCov end as r_shapeIyyIxyCov, 
case r_extendedness when 'null' then null else r_extendedness end as r_extendedness, 
case r_flagNegative when '0' then 0 when '1' then 1 else null end as r_flagNegative, 
case r_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as r_flagBadMeasCentroid, 
case r_flagPixEdge when '0' then 0 when '1' then 1 else null end as r_flagPixEdge, 
case r_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as r_flagPixInterpAny, 
case r_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as r_flagPixInterpCen, 
case r_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as r_flagPixSaturAny, 
case r_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as r_flagPixSaturCen, 
case r_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as r_flagBadPsfFlux, 
case r_flagBadApFlux when '0' then 0 when '1' then 1 else null end as r_flagBadApFlux, 
case r_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as r_flagBadModelFlux, 
case r_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as r_flagBadInstFlux, 
case r_flagBadCentroid when '0' then 0 when '1' then 1 else null end as r_flagBadCentroid, 
case r_flagBadShape when '0' then 0 when '1' then 1 else null end as r_flagBadShape, 
case i_psfFlux when 'null' then null else i_psfFlux end as i_psfFlux, 
case i_psfFluxSigma when 'null' then null else i_psfFluxSigma end as i_psfFluxSigma, 
case i_apFlux when 'null' then null else i_apFlux end as i_apFlux, 
case i_apFluxSigma when 'null' then null else i_apFluxSigma end as i_apFluxSigma, 
case i_modelFlux when 'null' then null else i_modelFlux end as i_modelFlux, 
case i_modelFluxSigma when 'null' then null else i_modelFluxSigma end as i_modelFluxSigma, 
case i_instFlux when 'null' then null else i_instFlux end as i_instFlux, 
case i_instFluxSigma when 'null' then null else i_instFluxSigma end as i_instFluxSigma, 
case i_apCorrection when 'null' then null else i_apCorrection end as i_apCorrection, 
case i_apCorrectionSigma when 'null' then null else i_apCorrectionSigma end as i_apCorrectionSigma, 
case i_shapeIx when 'null' then null else i_shapeIx end as i_shapeIx, 
case i_shapeIy when 'null' then null else i_shapeIy end as i_shapeIy, 
case i_shapeIxVar when 'null' then null else i_shapeIxVar end as i_shapeIxVar, 
case i_shapeIyVar when 'null' then null else i_shapeIyVar end as i_shapeIyVar, 
case i_shapeIxIyCov when 'null' then null else i_shapeIxIyCov end as i_shapeIxIyCov, 
case i_shapeIxx when 'null' then null else i_shapeIxx end as i_shapeIxx, 
case i_shapeIyy when 'null' then null else i_shapeIyy end as i_shapeIyy, 
case i_shapeIxy when 'null' then null else i_shapeIxy end as i_shapeIxy, 
case i_shapeIxxVar when 'null' then null else i_shapeIxxVar end as i_shapeIxxVar, 
case i_shapeIyyVar when 'null' then null else i_shapeIyyVar end as i_shapeIyyVar, 
case i_shapeIxyVar when 'null' then null else i_shapeIxyVar end as i_shapeIxyVar, 
case i_shapeIxxIyyCov when 'null' then null else i_shapeIxxIyyCov end as i_shapeIxxIyyCov, 
case i_shapeIxxIxyCov when 'null' then null else i_shapeIxxIxyCov end as i_shapeIxxIxyCov, 
case i_shapeIyyIxyCov when 'null' then null else i_shapeIyyIxyCov end as i_shapeIyyIxyCov, 
case i_extendedness when 'null' then null else i_extendedness end as i_extendedness, 
case i_flagNegative when '0' then 0 when '1' then 1 else null end as i_flagNegative, 
case i_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as i_flagBadMeasCentroid, 
case i_flagPixEdge when '0' then 0 when '1' then 1 else null end as i_flagPixEdge, 
case i_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as i_flagPixInterpAny, 
case i_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as i_flagPixInterpCen, 
case i_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as i_flagPixSaturAny, 
case i_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as i_flagPixSaturCen, 
case i_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as i_flagBadPsfFlux, 
case i_flagBadApFlux when '0' then 0 when '1' then 1 else null end as i_flagBadApFlux, 
case i_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as i_flagBadModelFlux, 
case i_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as i_flagBadInstFlux, 
case i_flagBadCentroid when '0' then 0 when '1' then 1 else null end as i_flagBadCentroid, 
case i_flagBadShape when '0' then 0 when '1' then 1 else null end as i_flagBadShape, 
case z_psfFlux when 'null' then null else z_psfFlux end as z_psfFlux, 
case z_psfFluxSigma when 'null' then null else z_psfFluxSigma end as z_psfFluxSigma, 
case z_apFlux when 'null' then null else z_apFlux end as z_apFlux, 
case z_apFluxSigma when 'null' then null else z_apFluxSigma end as z_apFluxSigma, 
case z_modelFlux when 'null' then null else z_modelFlux end as z_modelFlux, 
case z_modelFluxSigma when 'null' then null else z_modelFluxSigma end as z_modelFluxSigma, 
case z_instFlux when 'null' then null else z_instFlux end as z_instFlux, 
case z_instFluxSigma when 'null' then null else z_instFluxSigma end as z_instFluxSigma, 
case z_apCorrection when 'null' then null else z_apCorrection end as z_apCorrection, 
case z_apCorrectionSigma when 'null' then null else z_apCorrectionSigma end as z_apCorrectionSigma, 
case z_shapeIx when 'null' then null else z_shapeIx end as z_shapeIx, 
case z_shapeIy when 'null' then null else z_shapeIy end as z_shapeIy, 
case z_shapeIxVar when 'null' then null else z_shapeIxVar end as z_shapeIxVar, 
case z_shapeIyVar when 'null' then null else z_shapeIyVar end as z_shapeIyVar, 
case z_shapeIxIyCov when 'null' then null else z_shapeIxIyCov end as z_shapeIxIyCov, 
case z_shapeIxx when 'null' then null else z_shapeIxx end as z_shapeIxx, 
case z_shapeIyy when 'null' then null else z_shapeIyy end as z_shapeIyy, 
case z_shapeIxy when 'null' then null else z_shapeIxy end as z_shapeIxy, 
case z_shapeIxxVar when 'null' then null else z_shapeIxxVar end as z_shapeIxxVar, 
case z_shapeIyyVar when 'null' then null else z_shapeIyyVar end as z_shapeIyyVar, 
case z_shapeIxyVar when 'null' then null else z_shapeIxyVar end as z_shapeIxyVar, 
case z_shapeIxxIyyCov when 'null' then null else z_shapeIxxIyyCov end as z_shapeIxxIyyCov, 
case z_shapeIxxIxyCov when 'null' then null else z_shapeIxxIxyCov end as z_shapeIxxIxyCov, 
case z_shapeIyyIxyCov when 'null' then null else z_shapeIyyIxyCov end as z_shapeIyyIxyCov, 
case z_extendedness when 'null' then null else z_extendedness end as z_extendedness, 
case z_flagNegative when '0' then 0 when '1' then 1 else null end as z_flagNegative, 
case z_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as z_flagBadMeasCentroid, 
case z_flagPixEdge when '0' then 0 when '1' then 1 else null end as z_flagPixEdge, 
case z_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as z_flagPixInterpAny, 
case z_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as z_flagPixInterpCen, 
case z_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as z_flagPixSaturAny, 
case z_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as z_flagPixSaturCen, 
case z_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as z_flagBadPsfFlux, 
case z_flagBadApFlux when '0' then 0 when '1' then 1 else null end as z_flagBadApFlux, 
case z_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as z_flagBadModelFlux, 
case z_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as z_flagBadInstFlux, 
case z_flagBadCentroid when '0' then 0 when '1' then 1 else null end as z_flagBadCentroid, 
case z_flagBadShape when '0' then 0 when '1' then 1 else null end as z_flagBadShape, 
case y_psfFlux when 'null' then null else y_psfFlux end as y_psfFlux, 
case y_psfFluxSigma when 'null' then null else y_psfFluxSigma end as y_psfFluxSigma, 
case y_apFlux when 'null' then null else y_apFlux end as y_apFlux, 
case y_apFluxSigma when 'null' then null else y_apFluxSigma end as y_apFluxSigma, 
case y_modelFlux when 'null' then null else y_modelFlux end as y_modelFlux, 
case y_modelFluxSigma when 'null' then null else y_modelFluxSigma end as y_modelFluxSigma, 
case y_instFlux when 'null' then null else y_instFlux end as y_instFlux, 
case y_instFluxSigma when 'null' then null else y_instFluxSigma end as y_instFluxSigma, 
case y_apCorrection when 'null' then null else y_apCorrection end as y_apCorrection, 
case y_apCorrectionSigma when 'null' then null else y_apCorrectionSigma end as y_apCorrectionSigma, 
case y_shapeIx when 'null' then null else y_shapeIx end as y_shapeIx, 
case y_shapeIy when 'null' then null else y_shapeIy end as y_shapeIy, 
case y_shapeIxVar when 'null' then null else y_shapeIxVar end as y_shapeIxVar, 
case y_shapeIyVar when 'null' then null else y_shapeIyVar end as y_shapeIyVar, 
case y_shapeIxIyCov when 'null' then null else y_shapeIxIyCov end as y_shapeIxIyCov, 
case y_shapeIxx when 'null' then null else y_shapeIxx end as y_shapeIxx, 
case y_shapeIyy when 'null' then null else y_shapeIyy end as y_shapeIyy, 
case y_shapeIxy when 'null' then null else y_shapeIxy end as y_shapeIxy, 
case y_shapeIxxVar when 'null' then null else y_shapeIxxVar end as y_shapeIxxVar, 
case y_shapeIyyVar when 'null' then null else y_shapeIyyVar end as y_shapeIyyVar, 
case y_shapeIxyVar when 'null' then null else y_shapeIxyVar end as y_shapeIxyVar, 
case y_shapeIxxIyyCov when 'null' then null else y_shapeIxxIyyCov end as y_shapeIxxIyyCov, 
case y_shapeIxxIxyCov when 'null' then null else y_shapeIxxIxyCov end as y_shapeIxxIxyCov, 
case y_shapeIyyIxyCov when 'null' then null else y_shapeIyyIxyCov end as y_shapeIyyIxyCov, 
case y_extendedness when 'null' then null else y_extendedness end as y_extendedness, 
case y_flagNegative when '0' then 0 when '1' then 1 else null end as y_flagNegative, 
case y_flagBadMeasCentroid when '0' then 0 when '1' then 1 else null end as y_flagBadMeasCentroid, 
case y_flagPixEdge when '0' then 0 when '1' then 1 else null end as y_flagPixEdge, 
case y_flagPixInterpAny when '0' then 0 when '1' then 1 else null end as y_flagPixInterpAny, 
case y_flagPixInterpCen when '0' then 0 when '1' then 1 else null end as y_flagPixInterpCen, 
case y_flagPixSaturAny when '0' then 0 when '1' then 1 else null end as y_flagPixSaturAny, 
case y_flagPixSaturCen when '0' then 0 when '1' then 1 else null end as y_flagPixSaturCen, 
case y_flagBadPsfFlux when '0' then 0 when '1' then 1 else null end as y_flagBadPsfFlux, 
case y_flagBadApFlux when '0' then 0 when '1' then 1 else null end as y_flagBadApFlux, 
case y_flagBadModelFlux when '0' then 0 when '1' then 1 else null end as y_flagBadModelFlux, 
case y_flagBadInstFlux when '0' then 0 when '1' then 1 else null end as y_flagBadInstFlux, 
case y_flagBadCentroid when '0' then 0 when '1' then 1 else null end as y_flagBadCentroid, 
case y_flagBadShape when '0' then 0 when '1' then 1 else null end as y_flagBadShape
from object_stage