insert 

id, 
case coord_ra when 'null' then null else coord_ra end as coord_ra, 
case coord_decl when 'null' then null else coord_decl end as coord_decl, 
case coord_htmId20 when 'null' then null else coord_htmId20 end as coord_htmId20, 
case parent when 'null' then null else parent end as parent, 
flags_badcentroid, 
case centroid_sdss_x when 'null' then null else centroid_sdss_x end as centroid_sdss_x, 
case centroid_sdss_y when 'null' then null else centroid_sdss_y end as centroid_sdss_y, 
case centroid_sdss_xVar when 'null' then null else centroid_sdss_xVar end as centroid_sdss_xVar, 
case centroid_sdss_xyCov when 'null' then null else centroid_sdss_xyCov end as centroid_sdss_xyCov, 
case centroid_sdss_yVar when 'null' then null else centroid_sdss_yVar end as centroid_sdss_yVar, 
centroid_sdss_flags, 
flags_pixel_edge, 
flags_pixel_interpolated_any, 
flags_pixel_interpolated_center, 
flags_pixel_saturated_any, 
flags_pixel_saturated_center, 
flags_pixel_cr_any, 
flags_pixel_cr_center, 
case centroid_naive_x when 'null' then null else centroid_naive_x end as centroid_naive_x, 
case centroid_naive_y when 'null' then null else centroid_naive_y end as centroid_naive_y, 
case centroid_naive_xVar when 'null' then null else centroid_naive_xVar end as centroid_naive_xVar, 
case centroid_naive_xyCov when 'null' then null else centroid_naive_xyCov end as centroid_naive_xyCov, 
case centroid_naive_yVar when 'null' then null else centroid_naive_yVar end as centroid_naive_yVar, 
centroid_naive_flags, 
case centroid_gaussian_x when 'null' then null else centroid_gaussian_x end as centroid_gaussian_x, 
case centroid_gaussian_y when 'null' then null else centroid_gaussian_y end as centroid_gaussian_y, 
case centroid_gaussian_xVar when 'null' then null else centroid_gaussian_xVar end as centroid_gaussian_xVar, 
case centroid_gaussian_xyCov when 'null' then null else centroid_gaussian_xyCov end as centroid_gaussian_xyCov, 
case centroid_gaussian_yVar when 'null' then null else centroid_gaussian_yVar end as centroid_gaussian_yVar, 
centroid_gaussian_flags, 
case shape_sdss_Ixx when 'null' then null else shape_sdss_Ixx end as shape_sdss_Ixx, 
case shape_sdss_Iyy when 'null' then null else shape_sdss_Iyy end as shape_sdss_Iyy, 
case shape_sdss_Ixy when 'null' then null else shape_sdss_Ixy end as shape_sdss_Ixy, 
case shape_sdss_IxxVar when 'null' then null else shape_sdss_IxxVar end as shape_sdss_IxxVar, 
case shape_sdss_IxxIyyCov when 'null' then null else shape_sdss_IxxIyyCov end as shape_sdss_IxxIyyCov, 
case shape_sdss_IxxIxyCov when 'null' then null else shape_sdss_IxxIxyCov end as shape_sdss_IxxIxyCov, 
case shape_sdss_IyyVar when 'null' then null else shape_sdss_IyyVar end as shape_sdss_IyyVar, 
case shape_sdss_IyyIxyCov when 'null' then null else shape_sdss_IyyIxyCov end as shape_sdss_IyyIxyCov, 
case shape_sdss_IxyVar when 'null' then null else shape_sdss_IxyVar end as shape_sdss_IxyVar, 
shape_sdss_flags, 
case shape_sdss_centroid_x when 'null' then null else shape_sdss_centroid_x end as shape_sdss_centroid_x, 
case shape_sdss_centroid_y when 'null' then null else shape_sdss_centroid_y end as shape_sdss_centroid_y, 
case shape_sdss_centroid_xVar when 'null' then null else shape_sdss_centroid_xVar end as shape_sdss_centroid_xVar, 
case shape_sdss_centroid_xyCov when 'null' then null else shape_sdss_centroid_xyCov end as shape_sdss_centroid_xyCov, 
case shape_sdss_centroid_yVar when 'null' then null else shape_sdss_centroid_yVar end as shape_sdss_centroid_yVar, 
shape_sdss_centroid_flags, 
shape_sdss_flags_unweightedbad, 
shape_sdss_flags_unweighted, 
shape_sdss_flags_shift, 
shape_sdss_flags_maxiter, 
case flux_psf when 'null' then null else flux_psf end as flux_psf, 
case flux_psf_err when 'null' then null else flux_psf_err end as flux_psf_err, 
flux_psf_flags, 
case flux_psf_psffactor when 'null' then null else flux_psf_psffactor end as flux_psf_psffactor, 
flux_psf_flags_psffactor, 
flux_psf_flags_badcorr, 
case flux_naive when 'null' then null else flux_naive end as flux_naive, 
case flux_naive_err when 'null' then null else flux_naive_err end as flux_naive_err, 
flux_naive_flags, 
case flux_gaussian when 'null' then null else flux_gaussian end as flux_gaussian, 
case flux_gaussian_err when 'null' then null else flux_gaussian_err end as flux_gaussian_err, 
flux_gaussian_flags, 
case flux_gaussian_psffactor when 'null' then null else flux_gaussian_psffactor end as flux_gaussian_psffactor, 
flux_gaussian_flags_psffactor, 
flux_gaussian_flags_badcorr, 
case flux_sinc when 'null' then null else flux_sinc end as flux_sinc, 
case flux_sinc_err when 'null' then null else flux_sinc_err end as flux_sinc_err, 
flux_sinc_flags, 
case centroid_record_x when 'null' then null else centroid_record_x end as centroid_record_x, 
case centroid_record_y when 'null' then null else centroid_record_y end as centroid_record_y, 
case classification_extendedness when 'null' then null else classification_extendedness end as classification_extendedness, 
case aperturecorrection when 'null' then null else aperturecorrection end as aperturecorrection, 
case aperturecorrection_err when 'null' then null else aperturecorrection_err end as aperturecorrection_err, 
case refFlux when 'null' then null else refFlux end as refFlux, 
case refFlux_err when 'null' then null else refFlux_err end as refFlux_err, 
objectId, 
case coord_raVar when 'null' then null else coord_raVar end as coord_raVar, 
case coord_radeclCov when 'null' then null else coord_radeclCov end as coord_radeclCov, 
case coord_declVar when 'null' then null else coord_declVar end as coord_declVar, 
exposure_id, 
exposure_filter_id, 
case exposure_time when 'null' then null else exposure_time end as exposure_time, 
case exposure_time_mid when 'null' then null else exposure_time_mid end as exposure_time_mid, 
case cluster_id when 'null' then null else cluster_id end as cluster_id, 
case cluster_coord_ra when 'null' then null else cluster_coord_ra end as cluster_coord_ra, 
case cluster_coord_decl when 'null' then null else cluster_coord_decl end as cluster_coord_decl